### ISSUE TITLE
Extract startup_led et preview_led in an external plugin

### ISSUE THREAD

**Issue by werdeil** [pibooth/pibooth#127]
As we are introducing a new plugin system and as these 2 leds came from an external request and are not for me part of the core pibooth we shall remove them from pibooth and intergrate them in a dedicated plugin.

Note: I'm not sure it is easy for the startup_led.

**Comment by anxuae** [comment]
2 new hooks can be added in order to manage actions at `pibooth` startup and cleanup to manage to `startup_led `.

**Comment by sravel** [comment]
hello, I test use the __gpiozero__ lib (#131) and for the initialization you can use this : 
```self.led_startup = LED("BOARD" + config.get('CONTROLS', 'startup_led_pin'), initial_value=True)```

I implemented RGB led as plugin with gpiozero lib and i actually make some test. I can test add core led as plugin if you want.

**Comment by anxuae** [comment]
I propose to create a repository named `pibooth-lights` to move the extra lights in.
What do you think about this name?

**Comment by werdeil** [comment]
I would say pibooth-extra-lights to emphasze the fact that « standard » lights are not in this one.

**Comment by anxuae** [comment]
It seems great to me!

**Comment by anxuae** [comment]
LEDs are extracted.
First version of the plugin is now available on PyPi: https://pypi.org/project/pibooth-extra-lights
This issue can be closed
