### ISSUE TITLE
Add RGB config element available in config menu

### ISSUE THREAD

**Issue by werdeil** [pibooth/pibooth#128]
**Is your feature request related to a problem? Please describe.**
As config is big and the choice of text, background for display and final picture is quite important I think we shall be able to set them through the config menu

**Describe the solution you'd like**
Ideal: writing separately Red, Green and Blue value and have a preview square where the value is computed to show the color
Acceptable: a text setting where we put (R,G,B) directly.

**Describe alternatives you've considered**
A separated tool to generate the config at start

**Comment by anxuae** [comment]
I propose to ask to @ppizarror if such a widget can be added to pygame-menu

**Comment by ppizarror** [comment]
hmmm, such widget may be 3 different text boxes and a preview color. Something like this:
![image](https://user-images.githubusercontent.com/12925256/77271209-d69c2500-6c8c-11ea-9090-8262a832d9df.png)

**Comment by anxuae** [comment]
Hi @ppizarror, thanks for your quick comment ;-)
Yes this seems a good idea. To a void a too long widget, we could use the background of entry text to put the color:

![77271209-d69c2500-6c8c-11ea-9090-8262a832d9df](https://user-images.githubusercontent.com/25277953/77311262-0df7e980-6d00-11ea-8121-ec3ef899c250.png)

(managing font color in white when color is too dark)

**Comment by werdeil** [comment]
I prefer the first option, having the background changr is quite strange no?

**Comment by werdeil** [comment]
However if we have only one textview with the 3 values I find it more understandable (as it is updated once I have changed the 3 of them).

Color [ (23, 54, 123) ]

**Comment by ppizarror** [comment]
> However if we have only one textview with the 3 values I find it more understandable (as it is updated once I have changed the 3 of them).
> 
> Color [ (23, 54, 123) ]

but the user must enter a comma for each number, that's not so user-friendly. I think that 3 boxes with each number separated is much easier to use

**Comment by werdeil** [comment]
> user must enter a comma for each number

Yes indeed, this doesn't seems to be an issue for me as my first idea was to have something like on this website: https://www.w3schools.com/colors/colors_rgb.asp
User can specify the color either in RGB or in hex 

Or we keep only the RGB option and in this case let only the number editable (I don't know if you have already something for this in pygame-menu)

**Comment by ppizarror** [comment]
New version v2.2.0 online! This introduces color input widget.
