### ISSUE TITLE
Separate ISO Setting for preview picture

### ISSUE THREAD

**Issue by PatrickPahlke** [pibooth/pibooth#168]
Is it possible to add a separate ISO setting for the preview? We are using a manual flash device. If we configure the camera for a good preview picture it will be too bright. If we set it up for a good picture with the flash we don's see anything in the preview. 

Thank you very much

**Comment by anxuae** [comment]
Hi @PatrickPahlke 

We can image to give the possibility of setting 2 values in the config key `[CAMERA][iso]`.
I will have a look if it can easily be done.

**Comment by PatrickPahlke** [comment]
Thank you very much

Mit freundlichen Grüßen

Patrick Pahlke

Im Muckentäle 18
72488 Sigmaringen

Mobil: 0160 707 9365
E-Mail: pahlke-sigmaringen@hotmail.de


________________________________

**Comment by anxuae** [comment]
First implementation in #232 , to be tested with DSLR

**Comment by anxuae** [comment]
#232 merged in master
