### ISSUE TITLE
Need helps for text size changing

### ISSUE THREAD

**Issue by TheSuperpapi** [pibooth/pibooth#170]
Hello Guys,

Could you help me to increase this text size?

![image](https://user-images.githubusercontent.com/58975393/90984924-a1b43700-e578-11ea-9da2-eefa989ad2bd.png)

Thanks for your help,
Papi

**Comment by anxuae** [comment]
Hi @TheSuperpapi ,

Starting `pibooth` in debug mode (menu: General > Debug mode) let you see the reserved placeholders for texts.
All texts are automatically resized to fit the red rectangles.

You can try to split your text in more than 2 lines in order to have a better filling.

But, if the placeholder is not big enough for your needs, you have to change the code here below to increase the size of the red rectangle:

https://github.com/pibooth/pibooth/blob/b79ead1162e9ef546e1a7ef6178ce71a6286b454/pibooth/view/background.py#L270-L279

**Comment by TheSuperpapi** [comment]
Hello Anxuae,

Thanks for your reply.
You are confirming to me that I was looking the right file / direction and that I understood the method of auto text resize vs rectangle.

I'm pretty happy, it means that I begin to understand a bit your hard work :)

I'm learning a lot by try to understand everything :)

So now, I have to understand this part of the code line by line, and update it.

I have 2 weeks before my wedding, think will be ok.

I'm preparing my success story in // that you can have a overview below :)

![PTB](https://user-images.githubusercontent.com/58975393/91020806-378ca800-e5f3-11ea-8a32-9e2d090ea1ca.jpg)

Thanks again,
Papi

**Comment by werdeil** [comment]
Wow really nice setup ! Thanks a lot for sharing the photo, do you allow us to put it in the [wiki](https://github.com/pibooth/pibooth/wiki) page? If you have more photos to share we will be glad to add them too.

If you need help to change the line of code ask us, and maybe we can manage to have something that fits all needs in the code.

**Comment by TheSuperpapi** [comment]
Hi Werdeil,
Yes for sure, you can share the pictures, and if you need more details about the setup (component list, etc) just ask :)
Here more pictures :-)

I'll try to update the code by myself, I like to try before to ask :), it's a big challenge because I have no knowledge be I'm able now to aderstand when I read, juste have to learn a lot about formulas, commands, etc :-)

![thumbnail_IMG_20200824_203229](https://user-images.githubusercontent.com/58975393/91083438-9cbfb800-e64a-11ea-8c9d-5f247d0d140b.jpg)
![thumbnail_IMG_20200824_203235](https://user-images.githubusercontent.com/58975393/91083449-9f221200-e64a-11ea-8ca9-83f729552357.jpg)
![thumbnail_IMG_20200824_203247](https://user-images.githubusercontent.com/58975393/91083455-a0ebd580-e64a-11ea-9bb7-89447658cc88.jpg)
![thumbnail_IMG_20200824_203306](https://user-images.githubusercontent.com/58975393/91083462-a2b59900-e64a-11ea-9552-01020cebacd7.jpg)
![thumbnail_IMG_20200824_203318](https://user-images.githubusercontent.com/58975393/91083467-a47f5c80-e64a-11ea-800b-d2ce6be8265d.jpg)
