### ISSUE TITLE
No preview displayed using VNC remote viewer

### ISSUE THREAD

**Issue by babou7635** [pibooth/pibooth#174]
Hello les amis,

I have installed the very last version of the pibooth. I run, it works fine but unfortunately I have no preview screen. The application goes all the way. I get the requested photo (s). My concern is that there is no preview even though the timer is set to 5 sec in the configuration menu. So I have a black screen for 5 seconds and after that it displays my photo without problem.
I also set the "Preview Countdown" function to True but unfortunately I have no display of a count.

Is this normal?

Thank you for your help in advance because I am drying?

Thank 

**Environment**
 - OS [Raspbian Buster]
 - Camera [Rpi camera]
 - Pibooth version [2.0.0]
 - Pigame version [1.9.6]

**Comment by anxuae** [comment]
Hi @babou7635 ,

No, this behavior is not normal.

Can you tell me if you are using a DSLR camera also (hybrid mode) ?
What kind of screen are you using?

**Comment by babou7635** [comment]
Hello,
Thanks for your feedback.
I use the camera for the raspberry (Pi Noir Camera V2) only this one.
For the moment I use my raspberry connected in VNC. I don't have connected a screen directely to the raspberry.
I test with a screen to HDMI tomorow.
Tell me if i must to change my camera V2.

**Comment by anxuae** [comment]
Hello @babou7635 

VNCViewer is the cause. The preview is an overlay managed at GPU low level, thus it is not accessible using the VNC protocol.

See the post: https://raspberrypi.stackexchange.com/questions/29537/sending-raspberry-pi-camera-preview-to-a-laptop-running-vnc-viewer .

**Comment by babou7635** [comment]
Hello,

I use to HDMI via a screen and it's ok for me. All works !! It's very good.

Thanks ;)
