### ISSUE TITLE
Edition in the settings menu before exit are not taken into account

### ISSUE THREAD

**Issue by werdeil** [pibooth/pibooth#189]
**Describe the bug**
If a user change something in the settings menu (for example the footer text) and then leave the menu through the "exit" entry the pibooth stops and the changed setting is not stored.

**Steps to reproduce the bug**
1. Open pibooth
2. Open the settings menu
3. change one settings
4. exit the menu through the exit entry.

I think "exit" shall be rename to "exit pibooth" too, to avoid misleading behavior (I often think it will allow me to exit the menu).

**Comment by anxuae** [comment]
Fixed, see PR
