### ISSUE TITLE
Rotate Picture

### ISSUE THREAD

**Issue by sonkinshu** [pibooth/pibooth#196]
I need to invert the picture but its ignoring the changes I've made to the config file. Attempting to rotate 180.

**Comment by DJ-Dingo** [comment]
@sonkinshu I just tried 180 and it's working fine here - 180
with version 2.0.1 and raspberry pi cam

Remember to NOT have the pibooth program running when you make changes in the config.cfg
First Exit pibooth, Then open the config.cfg, Make changes and save and exit config cfg again. Then open pibooth again.

**Comment by werdeil** [comment]
@sonkinshu Did you managed to make it work? which setting in the config did you changed?

**Comment by anxuae** [comment]
Hi @sonkinshu ,

Have you solved your issue? If yes, can you close it?

Thanks

**Comment by dafunkychild** [comment]
Hello, I did follow the instructions but modifying rotation parameter in the config file as no effect.
