### ISSUE TITLE
Connection to Cups

### ISSUE THREAD

**Issue by MicroMast3r** [pibooth/pibooth#200]
Hello,

I have a problem with the connection to cups and don't know how to get this away.

pi@raspberrypi:~ $ pibooth
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
[ INFO    ] pibooth           : Installed plugins: 
[ INFO    ] pibooth           : Starting the photo booth application on Raspberry pi 3B+
[ INFO    ] pibooth           : Configuring Picamera camera ...
Traceback (most recent call last):
  File "/usr/local/bin/pibooth", line 10, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.7/site-packages/pibooth/booth.py", line 456, in main
    app = PiApplication(config, plugin_manager)
  File "/home/pi/.local/lib/python3.7/site-packages/pibooth/booth.py", line 126, in __init__
    self.count)
  File "/home/pi/.local/lib/python3.7/site-packages/pibooth/printer.py", line 36, in __init__
    self._conn = cups.Connection() if cups else None
AttributeError: module 'cups' has no attribute 'Connection'

i can see the printer in cups and also print test pages.
I want to use a Canon Selphy CP1300

**Comment by anxuae** [comment]
Can you run this command:

`pip freeze | grep pycups`

And send me the result?

**Comment by anxuae** [comment]
Hi @MicroMast3r 

What is the status of this bug? Do you solve it?

If yes, can I close this issue?

thanks

**Comment by anxuae** [comment]
No feedback since several months, I'm closing this issue.
Please re-open if necessary.
