### ISSUE TITLE
 New Plugin pibooth-nextcloud

### ISSUE THREAD

**Issue by ceeeeb** [pibooth/pibooth#203]
Hello,

I created an plugin to send the photos to nextcloud and you can access it afterwards via a QR code.

Are you interested in this plugin?

**Comment by werdeil** [comment]
Yes we are, can you give the link of the plugin here? We will have a look

**Comment by ceeeeb** [comment]
herefind the github link
https://github.com/ceeeeb/pibooth-nextcloud




<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Le mer. 4 nov. 2020 à 12:22, Vincent Verdeil <notifications@github.com> a
écrit :

**Comment by anxuae** [comment]
Hi @ceeeeb,

Thank for sharing your plugin and great job! It will be displayed when the visitor click on the link in the README section [Customize using plugins](https://github.com/pibooth/pibooth#customize-using-plugins).

However to integrate and move your repository in the `Pibooth` organisation (of course welcomed 😄), you will need to give me all the admin rights on you repository. So it is really up-to..

BR
anxuae

**Comment by ceeeeb** [comment]
Hi anxuae,

Can you give me your email address so I can give you the administrator
access

**Comment by anxuae** [comment]
Hi @ceeeeb 

I let you do the things if you want. But this issue can be closed

**Comment by DJ-Dingo** [comment]
@anxuae 

Curious, I can not see any info about this plugin, in the "link in the README section".
Did i look the wrong place, or you forget to insert it ?

**Comment by mozdi** [comment]
Hi @ceeeeb, @anxuae,
is this plugin still working with pibooth?
I couldn´t find it in the README section or on any other place where plugins are linked.

I´ve raised an issue in the plugin, because the installation using pip fails:
https://github.com/ceeeeb/pibooth-nextcloud/issues/1

BR Mozdi
