### ISSUE TITLE
Opening the menu while Picamera preview is on doesn't close the preview

### ISSUE THREAD

**Issue by werdeil** [pibooth/pibooth#204]
**Describe the bug**
As described in the title, if you open the menu while the preview is on, the menu opens and the preview stays on (on top of the menu).

2 solutions for me:
- Do not allow menu opening during the preview and capture part
or
- Force preview stop when the menu shows

@anxuae tell me which one you prefer

**Environment**
 - OS: Raspbian Buster
 - Camera : Rpi camera
 - Pibooth version 2.0.1

**Comment by anxuae** [comment]
Hello @werdeil 

Both are ok. Maybe it is more user-friendly to let opening the menu, it permit to stop the current sequence during tests for instance...

**Comment by werdeil** [comment]
It was one line of code so I didn't made a PR.
