### ISSUE TITLE
plugin with submenu

### ISSUE THREAD

**Issue by DJ-Dingo** [pibooth/pibooth#214]
Is it possible to create a Menu / Submenu for one plugin.
I have several plugins that is divided into 2 menu options, etc. "Setup and Text-Edit". 
It could be nice to have it gathered under 1 menu, with the 2 submenus "Setup" and "Text-Edit", for just that plugin.

**Comment by anxuae** [comment]
Hi @DJ-Dingo 

There is only one level of menu for the moment is pibooth. Thus short answer is : no, it is not possible.

I think that it will no be possible without rework the whole configuration structure:

- Handling several levels of sub-menu will make the generation of the graphical menu more complex
- The `INI` format of the configuration file does not support several levels of `sections`
