### ISSUE TITLE
 Canon EOS 1100D [ DSLR camera]

### ISSUE THREAD

**Issue by GiorgioIOT** [pibooth/pibooth#221]
sorry my english is not perfect.

problem with Canon Eos camera, Pibooth V.2.0.1 installed, crashes, I attach files with description.

`Pibooth version installed: 2.0.1
Listing all connected DSLR camera
00 : addr-> usb:001,005  name-> Canon EOS 1100D

================================================================================
Stating diagnostic of connected DSLR camera
* Preview compatible: True
* Capture compatible: True
/actions/syncdatetime
  Label       : Synchronize camera date and time with PC
  Readonly    : no
  Data type   : <class 'int'>
  Widget type : Toggle button (or check box)
  Current     : 0
  Choices     : [0, 1]
/actions/uilock
  Label       : UI Lock
  Readonly    : no
  Data type   : <class 'int'>
  Widget type : Toggle button (or check box)
  Current     : 2
  Choices     : [0, 1]
/actions/popupflash
  Label       : Popup Flash
  Readonly    : no
  Data type   : <class 'int'>
  Widget type : Toggle button (or check box)
  Current     : 2
  Choices     : [0, 1]
/actions/autofocusdrive
  Label       : Drive Canon DSLR Autofocus
  Readonly    : no
  Data type   : <class 'int'>
  Widget type : Toggle button (or check box)
  Current     : 0
  Choices     : [0, 1]
/actions/manualfocusdrive
  Label       : Drive Canon DSLR Manual focus
  Readonly    : no
  Data type   : <class 'str'>
  Widget type : Radio button
  Current     : None
  Choices     : ['Near 1', 'Near 2', 'Near 3', 'None', 'Far 1', 'Far 2', 'Far 3']
/actions/cancelautofocus
  Label       : Cancel Canon DSLR Autofocus
  Readonly    : no
  Data type   : <class 'int'>
  Widget type : Toggle button (or check box)
  Current     : 0
  Choices     : [0, 1]
/actions/eoszoom
  Label       : Canon EOS Zoom
  Readonly    : no
  Data type   : <class 'str'>
  Widget type : Text
  Current     : 0
  Choices     : n/a
/actions/eoszoomposition
  Label       : Canon EOS Zoom Position
  Readonly    : no
  Data type   : <class 'str'>
  Widget type : Text
  Current     : 0,0
  Choices     : n/a
/actions/viewfinder
  Label       : Canon EOS Viewfinder
  Readonly    : no
  Data type   : <class 'int'>
  Widget type : Toggle button (or check box)
  Current     : 0
  Choices     : [0, 1]
/actions/eosremoterelease
  Label       : Canon EOS Remote Release
  Readonly    : no
  Data type   : <class 'str'>
  Widget type : Radio button
  Current     : None
  Choices     : ['None', 'Press Half', 'Press Full', 'Release Half', 'Release Full', 'Immediate', 'Press 1', 'Press 2', 'Press 3', 'Release 1', 'Release 2', 'Release 3']
/actions/opcode
  Label       : PTP Opcode
  Readonly    : no
  Data type   : <class 'str'>
  Widget type : Text
  Current     : 0x1001,0xparam1,0xparam2
  Choices     : n/a
/settings/datetime
  Label       : Camera Date and Time
  Readonly    : no
  Data type   : <class 'int'>
  Widget type : Date entering
  Current     : 1614115278
  Choices     : n/a
/settings/reviewtime
  Label       : Quick Review Time
  Readonly    : no
  Data type   : <class 'str'>
  Widget type : Radio button
  Current     : 2 seconds
  Choices     : ['None', '2 seconds', '4 seconds', '8 seconds', 'Hold']
/settings/output
  Label       : Camera Output
  Readonly    : no
  Data type   : <class 'str'>
  Widget type : Radio button
  Current     : Off
  Choices     : ['TFT', 'PC', 'TFT + PC', 'MOBILE', 'TFT + MOBILE', 'PC + MOBILE', 'TFT + PC + MOBILE', 'Off']
/settings/movierecordtarget
  Label       : Recording Destination
  Readonly    : no
  Data type   : <class 'str'>
  Widget type : Radio button
  Current     : None
  Choices     : ['None']
/settings/evfmode
  Label       : EVF Mode
  Readonly    : no
  Data type   : <class 'str'>
  Widget type : Radio button
  Current     : 1
  Choices     : ['0', '1']
/settings/ownername
  Label       : Owner Name
  Readonly    : no
  Data type   : <class 'str'>
  Widget type : Text
  Current     :
  Choices     : n/a
/settings/artist
  Label       : Artist
  Readonly    : no
  Data type   : <class 'str'>
  Widget type : Text
  Current     :
  Choices     : n/a
/settings/copyright
  Label       : Copyright
  Readonly    : no
  Data type   : <class 'str'>
  Widget type : Text
  Current     :
  Choices     : n/a
/settings/customfuncex
  Label       : Custom Functions Ex
  Readonly    : no
  Data type   : <class 'str'>
  Widget type : Text
  Current     : b0,4,1,20,2,101,1,0,10f,1,0,2,2c,3,201,1,0,202,1,0,203,1,0,3,14,1,50e,1,0,4,38,4,701,1,0,704,1,0,70e,1,0,811,1,0,
  Choices     : n/a
/settings/focusinfo
  Label       : Focus Info
  Readonly    : no
  Data type   : <class 'str'>
  Widget type : Text
  Current     : eosversion=4,size=4272x2848,size2=4272x2848,points={{-1123,0,148,106},{-674,333,148,106},{-674,-333,148,106},{0,626,102,149},{0,0,190,183},{0,-626,102,149},{674,333,148,106},{674,-333,
[... -> see log file for full message]
  Choices     : n/a
/settings/autopoweroff
  Label       : Auto Power Off
  Readonly    : no
  Data type   : <class 'str'>
  Widget type : Text
  Current     : 0
  Choices     : n/a
/settings/depthoffield
  Label       : Depth of Field
  Readonly    : no
  Data type   : <class 'str'>
  Widget type : Text
  Current     : 0
  Choices     : n/a
/settings/capturetarget
  Label       : Capture Target
  Readonly    : no
  Data type   : <class 'str'>
  Widget type : Radio button
  Current     : Memory card
  Choices     : ['Internal RAM', 'Memory card']
/settings/capture
  Label       : Capture
  Readonly    : no
  Data type   : <class 'int'>
  Widget type : Toggle button (or check box)
  Current     : 0
  Choices     : [0, 1]
/settings/remotemode
  Label       : Remote Mode
  Readonly    : no
  Data type   : <class 'str'>
  Widget type : Text
  Current     : 1
  Choices     : n/a
/status/serialnumber
  Label       : Serial Number
  Readonly    : no
  Data type   : <class 'str'>
  Widget type : Text
  Current     : 4d829edf36154db4ae8ab7438d3a424a
  Choices     : n/a
/status/manufacturer
  Label       : Camera Manufacturer
  Readonly    : no
  Data type   : <class 'str'>
  Widget type : Text
  Current     : Canon Inc.
  Choices     : n/a
/status/cameramodel
  Label       : Camera Model
  Readonly    : no
  Data type   : <class 'str'>
  Widget type : Text
  Current     : Canon EOS 1100D
  Choices     : n/a
/status/deviceversion
  Label       : Device Version
  Readonly    : no
  Data type   : <class 'str'>
  Widget type : Text
  Current     : 3-1.0.5
  Choices     : n/a
/status/vendorextension
  Label       : Vendor Extension
  Readonly    : no
  Data type   : <class 'str'>
  Widget type : Text
  Current     : None
  Choices     : n/a
/status/model
  Label       : Camera Model
  Readonly    : no
  Data type   : <class 'str'>
  Widget type : Text
  Current     : 2147484296
  Choices     : n/a
/status/ptpversion
  Label       : PTP Version
  Readonly    : no
  Data type   : <class 'str'>
  Widget type : Text
  Current     : 256
  Choices     : n/a
/status/
  Label       : Battery Level
  Readonly    : yes
  Data type   : <class 'str'>
  Widget type : Text
  Current     : 100%
  Choices     : n/a
/status/batterylevel
  Label       : Battery Level
  Readonly    : no
  Data type   : <class 'str'>
  Widget type : Text
  Current     : 100%
  Choices     : n/a
/status/lensname
  Label       : Lens Name
  Readonly    : no
  Data type   : <class 'str'>
  Widget type : Text
  Current     : EF-S18-55mm f/3.5-5.6 III
  Choices     : n/a
/status/eosserialnumber
  Label       : Serial Number
  Readonly    : no
  Data type   : <class 'str'>
  Widget type : Text
  Current     : 323074015529
  Choices     : n/a
/status/shuttercounter
  Label       : Shutter Counter
  Readonly    : no
  Data type   : <class 'str'>
  Widget type : Text
  Current     : 13116
  Choices     : n/a
/status/availableshots
  Label       : Available Shots
  Readonly    : no
  Data type   : <class 'str'>
  Widget type : Text
  Current     : 1098
  Choices     : n/a
/imgsettings/imageformat
  Label       : Image Format
  Readonly    : no
  Data type   : <class 'str'>
  Widget type : Radio button
  Current     : RAW + Large Fine JPEG
  Choices     : ['Large Fine JPEG', 'Large Normal JPEG', 'Medium Fine JPEG', 'Medium Normal JPEG', 'Small Fine JPEG', 'Small Normal JPEG', 'Smaller JPEG', 'Tiny JPEG', 'RAW + Large Fine JPEG', 'RAW']
/imgsettings/imageformatsd
  Label       : Image Format SD
  Readonly    : no
  Data type   : <class 'str'>
  Widget type : Radio button
  Current     : RAW + Large Fine JPEG
  Choices     : ['Large Fine JPEG', 'Large Normal JPEG', 'Medium Fine JPEG', 'Medium Normal JPEG', 'Small Fine JPEG', 'Small Normal JPEG', 'Smaller JPEG', 'Tiny JPEG', 'RAW + Large Fine JPEG', 'RAW']
/imgsettings/iso
  Label       : ISO Speed
  Readonly    : no
  Data type   : <class 'str'>
  Widget type : Radio button
  Current     : Auto
  Choices     : ['Auto']
/imgsettings/whitebalance
  Label       : WhiteBalance
  Readonly    : no
  Data type   : <class 'str'>
  Widget type : Radio button
  Current     : Auto
  Choices     : ['Auto']
/imgsettings/whitebalancexa
  Label       : WhiteBalance X A
  Readonly    : no
  Data type   : <class 'str'>
  Widget type : Text
  Current     : 0
  Choices     : n/a
/imgsettings/whitebalancexb
  Label       : WhiteBalance X B
  Readonly    : no
  Data type   : <class 'str'>
  Widget type : Text
  Current     : 0
  Choices     : n/a
/imgsettings/colorspace
  Label       : Color Space
  Readonly    : no
  Data type   : <class 'str'>
  Widget type : Radio button
  Current     : sRGB
  Choices     : ['sRGB']
/capturesettings/exposurecompensation
  Label       : Exposure Compensation
  Readonly    : no
  Data type   : <class 'str'>
  Widget type : Radio button
  Current     : 0
  Choices     : ['0']
/capturesettings/focusmode
  Label       : Focus Mode
  Readonly    : no
  Data type   : <class 'str'>
  Widget type : Radio button
  Current     : AI Focus
  Choices     : ['AI Focus']
/capturesettings/aspectratio
  Label       : Aspect Ratio
  Readonly    : no
  Data type   : <class 'str'>
  Widget type : Radio button
  Current     : 3:2
  Choices     : ['3:2']
/capturesettings/storageid
  Label       : Storage Device
  Readonly    : no
  Data type   : <class 'str'>
  Widget type : Text
  Current     : 00020001
  Choices     : n/a
/capturesettings/autoexposuremode
  Label       : Canon Auto Exposure Mode
  Readonly    : no
  Data type   : <class 'str'>
  Widget type : Radio button
  Current     : Green
  Choices     : ['P', 'TV', 'AV', 'Manual', 'Bulb', 'A_DEP', 'DEP', 'Custom', 'Lock', 'Green', 'Night Portrait', 'Sports', 'Portrait', 'Landscape', 'Closeup', 'Flash Off']
/capturesettings/drivemode
  Label       : Drive Mode
  Readonly    : no
  Data type   : <class 'str'>
  Widget type : Radio button
  Current     : Single
  Choices     : ['Single', 'Timer 10 sec', 'Continuous timer']
/capturesettings/picturestyle
  Label       : Picture Style
  Readonly    : no
  Data type   : <class 'str'>
  Widget type : Radio button
  Current     : Standard
  Choices     : ['Standard']
/capturesettings/aperture
  Label       : Aperture
  Readonly    : no
  Data type   : <class 'str'>
  Widget type : Radio button
  Current     : implicit auto
  Choices     : ['implicit auto']
/capturesettings/shutterspeed
  Label       : Shutter Speed
  Readonly    : no
  Data type   : <class 'str'>
  Widget type : Radio button
  Current     : auto
  Choices     : ['auto']
/capturesettings/meteringmode
  Label       : Metering Mode
  Readonly    : no
  Data type   : <class 'str'>
  Widget type : Radio button
  Current     : Evaluative
  Choices     : ['Evaluative']
/capturesettings/bracketmode
  Label       : Bracket Mode
  Readonly    : no
  Data type   : <class 'str'>
  Widget type : Radio button
  Current     : Unknown value 0000
  Choices     : ['Unknown value 0000']
/capturesettings/aeb
  Label       : Auto Exposure Bracketing
  Readonly    : no
  Data type   : <class 'str'>
  Widget type : Radio button
  Current     : off
  Choices     : ['off']
/capturesettings/alomode
  Label       : Auto Lighting Optimization
  Readonly    : no
  Data type   : <class 'str'>
  Widget type : Radio button
  Current     : Standard (disabled in manual exposure)
  Choices     : ['Standard (disabled in manual exposure)']
/other/d402
  Label       : PTP Property 0xd402
  Readonly    : yes
  Data type   : <class 'str'>
  Widget type : Text
  Current     : Canon EOS 1100D
  Choices     : n/a
/other/d407
  Label       : PTP Property 0xd407
  Readonly    : yes
  Data type   : <class 'str'>
  Widget type : Text
  Current     : 1
  Choices     : n/a
/other/d406
  Label       : PTP Property 0xd406
  Readonly    : no
  Data type   : <class 'str'>
  Widget type : Text
  Current     : Unknown Initiator
  Choices     : n/a
/other/d303
  Label       : PTP Property 0xd303
  Readonly    : yes
  Data type   : <class 'str'>
  Widget type : Text
  Current     : 1
  Choices     : n/a
/other/5001
  Label       : Battery Level
  Readonly    : yes
  Data type   : <class 'str'>
  Widget type : Menu widget (same as Radio)
  Current     : 100
  Choices     : ['100', '0', '75', '0', '50']

================================================================================
Testing commands used by pibooth
Setting option imgsettings/iso="100"
   -> invalid value '100' for option iso (possible choices: ['Auto'])
   -> unsupported setting imgsettings/iso=100 (nothing configured on DSLR)
Setting option settings/capturetarget="Memory card"
Getting option actions/viewfinder=0
Setting option actions/viewfinder="1"
Take capture preview
Setting option actions/viewfinder="0"
Take a capture

================================================================================
ABORT   : exception occures: [-110] I/O in progress
If you are investigating why pibooth does not work with your DSLR camera,
please paste the content of generated file 'diagnostic.log'
on https://github.com/pibooth/pibooth/issues
`

the system is installed on Raspberry pi 4

**Comment by werdeil** [comment]
Hi @GiorgioIOT I don't think the crash comes from the use of a Canon 1100D as we are using this model on our version. Can you tell us more about the crash? When does it happen?

**Comment by GiorgioIOT** [comment]
> Ciao @GiorgioIOT Non credo che l'incidente derivi dall'uso di una Canon 1100D dato che stiamo usando questo modello sulla nostra versione. Puoi dirci di più sull'incidente? Quando succederà?

Hi Werdeil, I am using the Canon (Camera) in automatic mode.
Pibooth app in FullScreen mode, when I start I use button 1 to start the procedure, I choose between 4 photos or 1 photo, it starts with the vision of the Raspberry camera, I wait for the pause, take the photo with the Canon, I realize that it also starts the flas on the Canon, I await the vision for the press and goes to Oops.
I check on the Canon and on the sd card I find the picture taken.
Pygame version 1.9.6

**Comment by werdeil** [comment]
Ok so the issue is coming when pibooth tries to download the file from the Canon, does it have a SD card in it, with enough space?

**Comment by GiorgioIOT** [comment]
verifying SD from CANON and Raspberry, they have enough space to save photos.
I worked on the Canon setting only normal photos without RAW, I'm checking that it works. Do you recommend that you leave the Canon like this and lose the RAW photos?

**Comment by werdeil** [comment]
Yes if the issue was that you used RAW, put only jpg ones, we don't use raws and it can indeed create issue when downloading them as we don't expect to have anything else than jpg.

**Comment by GiorgioIOT** [comment]
I don't know what happened, but it doesn't work anymore, not even from Camera Raspberry !!!!!!
It worked for a while with the Canon, I installed Google Photo.
BUT I don't think that's the problem.
He saves the photo and then falls ....

**Comment by werdeil** [comment]
We may need more info to help you with this new fail: can you provide us some logs?

**Comment by GiorgioIOT** [comment]
I restored the pibooth.cfg file, I noticed that there are brackets and commas on the string and number entries, restoring it seems to work, I did not understand how to insert the google token on chat_id, is there any guide?

I realized that when I enter the pibooth graphic menu and exit this file is generated with brackets and commas.

**Comment by werdeil** [comment]
Seems that you have the issue with the last pygame-menu version, we made a fix https://github.com/pibooth/pibooth/commit/0096604b09d65f7cae3880d78a0bb14defff27d0 but didn't release a new version yet.

You can either try to install the development version or downgrade only the pygame-menu module as discussed here https://github.com/pibooth/pibooth/issues/212#issuecomment-763044955

**Comment by anxuae** [comment]
Hi @GiorgioIOT 

Did you solve your issue? If yes, please close this issue.

BR
anxuae

**Comment by GiorgioIOT** [comment]
the problem was solved by installing Pygame as described by (werdeil)
