### ISSUE TITLE
Touchscreen question.

### ISSUE THREAD

**Issue by DJ-Dingo** [pibooth/pibooth#250]
I have a Dell e2014T touch screen, mainly used it because it has a protective glass, and children like to point and touch the screen.

But how does the touchscreen work. I have not been able to get it to respond at all. I know it worked in the old days on some "Raspberry pi 2" projects but have not used it since. 

The question is whether this monitor is supported at all in the newer versions of Raspberry Pi OS., Or do I need to do something specific to make it work with Pibooth ?

**Comment by anxuae** [comment]
Hi @DJ-Dingo 

`pibooth` is built on to of `pygame` library, thus if your screen work with pygame, it will work with pibooth.
However I never try to do that. On this website, they use the same screen than you on a Raspberry Pi: https://projects-raspberry.com/digital-music-stand-raspberry-pi-touchscreen : have a look at `step 2`.

If you connect your screen, does the touches work (for instance clicking on the menu bar of the pi desktop)?

**Comment by werdeil** [comment]
And to add to @anxuae questions, do you have issue with a physical keyboard or with a touchscreen and the virtual keyboard?

**Comment by DJ-Dingo** [comment]
> If you connect your screen, does the touches work (for instance clicking on the menu bar of the pi desktop)?

No, it dont. But i give step 2 a try again. :-)

**Comment by DJ-Dingo** [comment]
Gonna close this for now, since it has nothing to do with Pibooth :-)

I am still trying to get it to wotk, but without any success yet.
