### ISSUE TITLE
Move docs to readthedocs

### ISSUE THREAD

**Issue by sravel** [pibooth/pibooth#251]
Readme is very big and if you want I can work to build a readthedocs website like this using sphinx:

![image](https://user-images.githubusercontent.com/11534773/119807168-2e629b80-bee3-11eb-980b-8b2b1457b58c.png)

doc is automatic update when git commit.

**Comment by anxuae** [comment]
Hi @sravel , 

this is a good idea. I think you have almost do the job, can you propose a PR?
I have setup the Readthedoc project: https://pibooth.readthedocs.io/en/latest/

All documentation should be kept in the `docs/` folder.
We could reduce the `README.rst` to the strict minimum and by adding a link to the documentation

**Comment by sravel** [comment]
![image](https://user-images.githubusercontent.com/11534773/120196369-127f3280-c220-11eb-9b6a-2d9ed9da9587.png)

**Comment by anxuae** [comment]
Merge done
