### ISSUE TITLE
Shortcut

### ISSUE THREAD

**Issue by arthur5640** [pibooth/pibooth#257]
Hello, is it possible to put a shortcut on the desktop

**Comment by anxuae** [comment]
Yes it is possible, follow this instructions: https://raspberrytips.com/desktop-shortcuts-on-raspberry-pi
(out of the scope of `pibooth` because solution is OS dependent)

**Comment by anxuae** [comment]
The shortcut is present in the folder : `/home/pi/.config/autostart/`
