### ISSUE TITLE
Rotation of only RPI-HQ camera but not Nikon

### ISSUE THREAD

**Issue by sravel** [pibooth/pibooth#272]
**Describe the bug**
I use both camera
- RPI-HQ-CAMERA
- Nikon D90

I want to make rotation of the RPI camera with 90°, but not Nikon camera.
But acutally both was rotate

**Steps to reproduce the bug**
1. Go to config.txt and change 
```
# Rotation of the camera: 0, 90, 180 or 270
rotation = 90
```
2. run pibooth with 2 camera

**Environment**
 - OS Raspbian last
 - Camera HQ Rpi camera + Nikon D90
 - Pibooth version dev

**Comment by anxuae** [comment]
Hi @sravel ,

This is not a bug but a feature. However, we can make an enhancement in order to let the choice as it is done for the ``iso`` option
