### ISSUE TITLE
Automatically print a photo, and not display the prompt

### ISSUE THREAD

**Issue by anxuae** [pibooth/pibooth#273]
Printing question: is there a way to automatically print a photo, and not display the prompt?

I'd prefer not to wire up an additional button or UI for folks, and just have a single print be automatic; similar to the way "traditional" photo booths work.

_Originally posted by @mattdsteele in https://github.com/pibooth/pibooth/issues/42#issuecomment-875744758_

**Comment by anxuae** [comment]
@mattdsteele I'ved opened an issue, because for the moment, there is no way to it, but it could be a useful improvement

**Comment by mattdsteele** [comment]
+1 for this config option 🎉 

For my use case, I'd also like for this to work with `max_pages`, as we'd want to stop printing after the paper has been exhausted.

**Comment by NiraCity** [comment]
These are my setting.
This is easier than described above

# Name of the printer defined in CUPS (or use the 'default' one)
printer_name = default

# Print options passed to the printer, shall be a valid Python dictionary
printer_options = {}

# How long is the print view in seconds (0 to skip it)
printer_delay = 10

# Number of pages automatically sent to the printer (or use 'max' to reach max duplicate)
auto_print = 1

# Maximum number of printed pages before warning on paper/ink levels (-1 = infinite)
max_pages = -1

# Maximum number of duplicate pages sent to the printer (avoid paper waste)
max_duplicates = 3

# Print 1, 2, 3 or 4 picture copies per page
pictures_per_page = 1
