### ISSUE TITLE
Assets

### ISSUE THREAD

**Issue by DennisD88** [pibooth/pibooth#285]
Is it possible to change the assets images? So can I create a own look and feel.

**Comment by anxuae** [comment]
We could generate an asset folder in the config directory, the user will be responsible to set asset with correct size.

@werdeil what your feeling?

**Comment by DennisD88** [comment]
Where can I find the asset folder on the raspberry, I search for it but I can't find.

**Comment by anxuae** [comment]
It should be there: ~/. local/lib/pythonX.Y/site-packages/pibooth

**Comment by DennisD88** [comment]
Thank for your quick response. I look ad the lib folder. I have a few Python version;

- Python 2.7
- Python 3
- Python 3.7
No of them has a folder with the name site-packages. When I search in the lib folder on site-packages or pibooth I find no folder.

**Comment by anxuae** [comment]
Try this command in a console:
```
python3 -c "import pibooth;print(pibooth.__file__)"
```

It should print the location on the pibooth directory

**Comment by DennisD88** [comment]
Hi,

Thanks for the commandline. I know location: /usr/local/lib/python3.7/dist-packages/pibooth/__init__.py

But when I go to this folder, my pi says the path is not valid.
De opgegeven map '/usr/local/lib/python3.7/dist-packages/pibooth/__init__.py' is niet geldig

**Comment by anxuae** [comment]
The path to the assets folder is `usr/local/lib/python3.7/dist-packages/pibooth/pictures/assets`

**Comment by DennisD88** [comment]
I know, but I don't find the folder dist-packages in the python3.7 folder.

**Comment by anxuae** [comment]
What is the result of the command:

`sudo ls /usr/local/lib/python3.7/dist-packages/pibooth/pictures/assets`

**Comment by werdeil** [comment]
> We could generate an asset folder in the config directory, the user will be responsible to update asset with correct size.
> 
> @werdeil what your feeling?

We already had a discussion about something like that some months ago (https://github.com/pibooth/pibooth/issues/122). As we are doing some processing to the asset like changing the color to match the text color or resizing them to fit the screen I find it specific enough to not see at a configurable part.

I think it is acceptable to consider that the rare user that want to change it fork the code to do it.

**Comment by anxuae** [comment]
Ok, agree with you.
@DennisD88 so best is to modify your self the pibooth source code . Did you found how to to it?

If yes, can you close the issue?

Thanks

**Comment by danamaki** [comment]
Hello. When I want to change images in /usr/local/lib/python3.7/dist-packages/pibooth/pictures/assets I don't have permissions to do it in FTP. What is the solution please. Thank you and congratulations for your work.
