### ISSUE TITLE
VIDIOC_QUERYCTL: Innapropriaite ioctl for device

### ISSUE THREAD

**Issue by tityann** [pibooth/pibooth#288]
i try to use pibooth with arducam pivariety 16 MP on a raspberry 4 with the last raspi os 
the camera works, i already took a photo (driver ok)
when i run pibooth, the window is black and in the window behind the first, i have the message:
VIDIOC_QUERYCTL: Innapropriaite ioctl for device

could you please help me to make work pibooth
thanks

**Comment by anxuae** [comment]
Hi @tityann 

Thanks for report. When you say that "camera works", which command did you use to test it?

pibooth use picamera library to handle the camera. I guess that arducam is not supported. But a driver could be developed

**Comment by tityann** [comment]
hello
thanks for your answer.
arducam pivariety use libcamera
i test a photo with:
libcamera-still -t 5000 -o test.jpg

sorry for my english, i am french : i don't know what a PR is
thanks

**Comment by anxuae** [comment]
PR is a "Pull Request" to propose a code with arducam driver implementation. Sorry but I can't do it, I have no arducam

**Comment by tityann** [comment]
hello
i am not able to make code
i asked help here #290

**Comment by tityann** [comment]
@anxuae 
hello, there were no answer on my ask help #290 
i will search myself a bit more
when you say , my camera need a driver implementation in photobbooth, i don't understand why you sayr driver
my camera has v4l2 support, for intitialisation, pibooth don't use it ?
thanks

**Comment by anxuae** [comment]
Can you post the complete log file? I believe that error is coming from OpenCV library, but I need to be sure

**Comment by anxuae** [comment]
I close this issue: error is coming from the invalid port in OpenCV camera
