### ISSUE TITLE
Bluetooth PRINTER

### ISSUE THREAD

**Issue by SergioMuinhos** [pibooth/pibooth#291]
Hello, I am looking for how to print from pibooth to a bluetooth printer since with the following command I can do it but not from the program.
obexftp --nopath --noconn --uuid none --bluetooth C4: 30: 00: 00: 7E: 41 --channel 4 - p image.png

Could you help me to install the printer by MAC?
Regards

**Comment by stephj915** [comment]
I am also interested in adding this type of printer. I have an HP Sprocket too, that works with obexftp but I haven't found how to link it with CUPS.
Thanks for your help.

**Comment by anxuae** [comment]
So, if it is not possible with CUPS, you can make a plugin to hack the default printer:
You can try this (I didn't test it, so you may have to debug it)

```python

"""Plugin to send pictures to a Bluetooth printer."""

import subprocess
import pibooth
from pibooth.utils import LOGGER

__version__ = "1.0.0"

def print_picture(filename, copies):
    subprocess.run(['obexftp', '--nopath', '--noconn', '--uuid', 'none', '--bluetooth', 'C4: 30: 00: 00: 7E: 41', '--canal', '4', '-p', filename])
    LOGGER.debug("File '%s' sent to the printer", filename)

@pibooth.hookimpl
def pibooth_startup(app):
    app.printer.print_file = print_picture

```

**Comment by stephj915** [comment]
Your plugin worked !
Just one changement : 'canal' by 'channel' .

Thank you !

**Comment by SergioMuinhos** [comment]
HI, I am trying to install the plugin and don't print the image.
I try manually and It works but when I created the file hp_printer.py with the code and paste in the folder plugin and doesn't print anything, I set another  wireless printer as default printer on the  RaspberryOS system and put it in the config file pibooth. And It does not work.
Can you tell me the steps to set up it correctly?
Thanks!

**Comment by SergioMuinhos** [comment]
Hi again,
I return to the Sprocket printer with pibooth,
I have just update and apply the plugin, but not print any image and works with obexftp.
This is the logs.
![image](https://user-images.githubusercontent.com/27500156/180486744-86bcc97a-1eca-4559-a098-b5b17c34f147.png)
Thanks
