### ISSUE TITLE
CP1000 printer disabled in CUPS when no more paper

### ISSUE THREAD

**Issue by anxuae** [pibooth/pibooth#296]
Hi, i have a canon CP1000 printer and when there is no more paper, The state of the printer go to “En pause – “Printer error: No Paper (03)” in CUPS then a have to manualy start the printer on CUPS.
The commande `cupsenable Canon_CP1000` allow to restart the printer and the printing work again.

I would like to add this command on my pibooth but i'm not a programmer and i don't find where i could do this on the programme. Could you advise me, thank.

_Originally posted by @HBTphoto in https://github.com/pibooth/pibooth/issues/269#issuecomment-952857087_

**Comment by anxuae** [comment]
Hi @HBTphoto it seems that the command has worked because the crash appears at line 113, after the command. By the way, I can't tell you what's the reason.

Maybe you can try to run the shell command using subprocess module?

**Comment by HBTphoto** [comment]
ok i could try, but i am not sure how i sould do ?
import subprocess (lines 19)
Then, line 102
subprocess.run(["ls", "-l"]) 

But how write the commande with subprocess ? if i understand well, it will allow to run my command without disturb the pibooth console ?

**Comment by anxuae** [comment]
I have no idea if there is an impact or not. You have to try:

subprocess.run('cupsenable', 'Canon_CP1000')

**Comment by HBTphoto** [comment]
I have error with the command syntax :
IndentationError: unident does not match any outer indentation level

**Comment by anxuae** [comment]
Some news?

**Comment by anxuae** [comment]
If you need help, please re-open the issue
