### ISSUE TITLE
User live preview is too dark using Raspberry Pi Camera

### ISSUE THREAD

**Issue by AndPDale** [pibooth/pibooth#304]
Hi,

I am using the Raspberry Pi camera V1 for user live preview with a Nikon D5600 to take the users photograph. 

I have found that the user live preview video whilst running pibooth is darker than if I run it using raspistill.

Is there a way to increase the brightness of the pibooth preview to replicate that seen using raspistill?

**Environment**
 - OS Raspbian Buster 10
 - Camera Raspberry pi V1 camera + Nikon D5600
 - Pibooth version 2.0.4
 - Raspberry pi 4 Model B

**Comment by anxuae** [comment]
Hi,

Try to change iso value in the config

**Comment by AndPDale** [comment]
Thanks, I will give that a go

**Comment by anxuae** [comment]
Hi @AndPDale , did you solve your issue?
