### ISSUE TITLE
FTP upload

### ISSUE THREAD

**Issue by DennisD88** [pibooth/pibooth#306]
I want to use the FTP upload plugin. But I can't place it in the plugin folder. I get a Access Denied message. Is it possible to install the plugin with a sudo command or have somebody a solution for me.

**Comment by werdeil** [comment]
You can put the plugin file wherever you want and simply put the path to it in the config.

**Comment by DennisD88** [comment]
Okay, I must change the config file in the root of the PiBooth folder with the path to the plugin?

**Comment by werdeil** [comment]
Yes change the pibooth.cfg file (by running `pibooth --config`)

You will find a line starting with: `plugins =`, just add the path to your custom plugin here:
```
plugins = /path/to/my/plugin.py
```

**Comment by Xasch** [comment]
where can I find the plugin

**Comment by damienhart** [comment]
https://pypi.org/search/?q=pibooth

**Comment by sravel** [comment]
Hello I also develop a SFTP plugin but I don't test on last version.
If you want to try some code you cna acces here
https://github.com/sravel/pibooth-sftp
I never push plugin on pypi so can't use pip3 install
but if you clone then install plugin with
python3 -m pip install .

**Comment by anxuae** [comment]
Seems to be solved.

**Comment by delmeer** [comment]
How to set the remote ftp path?
