### ISSUE TITLE
PIBOOTH KEEPS CRASHING

### ISSUE THREAD

**Issue by 1stTimerRick** [pibooth/pibooth#308]
[pibooth.log](https://github.com/pibooth/pibooth/files/7819266/pibooth.log)

I have tried this with the 8 steps and with the unofficial version and I get the same thing every time.  I typein pibooth to start the program then it goes to the number of pictures to select and then it crashes.  See attached file.  Please help.

**Comment by anxuae** [comment]
Hi, there is a issue with your DSLR, be sure that you are in manual mode, no autofocus

**Comment by 1stTimerRick** [comment]
Thx.  It was my DSLR camera malfunctioning.  I replaced it with picamera and everything is working fine.
