### ISSUE TITLE
Accessing counters from plugin

### ISSUE THREAD

**Issue by zapsterdk** [pibooth/pibooth#310]
Hi,
First of all thanks for a great and fun package!

I'm testing a bit on this now, and wondering if there are any easy ways to access the image/print counters from a plug-in? And also resetting these?

Also just for future releases it might be an idea to add a quick password to the menu. My friends are quite the investigating and curious types that tent to find menus like this... Just an idea =)

Stay safe!
\Zapsterdk

**Comment by DJ-Dingo** [comment]
I use this "app.count.taken app.count.printed app.count.forgotten app.count.remaining_duplicates" 
in my plugin - pibooth-lcd-display 2.0.0  -  check it on pypi - https://pypi.org/project/pibooth-lcd-display/
or https://pypi.org/search/?q=pibooth

I allso use it in my pibooth-oled-display (not released on pypi with install yet, but works if you refers to it in the cgf file)
https://github.com/DJ-Dingo/pibooth-oled-display

I like the "quick password" to menu, only problem is when i forget the keyboard.
So an extra button for menu could be nice too.
