### ISSUE TITLE
pibooth "oops. something went wrong"

### ISSUE THREAD

**Issue by Carl8210** [pibooth/pibooth#313]
Hi,
Im new to github, pibooth and pi's in general.  Most i've done is so far is install retropie and then i decided to try and make a photobooth with my pi 3b, and so I downloaded pibooth.  I've gone through the setup and had pibooth take a photo, after said photo is taken pibooth states something went wrong and goes back to the main menu.
gphoto2 capture image and download works fine so i decided to click the link from pibooth and post my log file here, Hopefully someone can help.
Thanks
[pibooth.log](https://github.com/pibooth/pibooth/files/8004775/pibooth.log)
s
More info: I'm using the buster image for the pi, and the camera is a cannon powershot sx730hs
the diag report is below
[diagnostic.log](https://github.com/pibooth/pibooth/files/8004984/diagnostic.log)

**Comment by Carl8210** [comment]
Still no idea whats going on, but taking a closer look at the camera, it seems that as pibooth counts down and trys to take the picture, the camera seems to receive the request but not actually take a photo, which means pibooth can't retrieve a photo and sends up the error message.  I've installed another photobooth program which works with the camera using gphoto2, but i really wanted Pibooth because of the plugin options.

**Comment by anxuae** [comment]
Hi @Carl8210 , put your DSLR in manual mode. ( According to the logs, you are in `P`)

**Comment by Carl8210** [comment]
Hi anxuae,
Tried that, I've tried on every setting the camera has, all bring the same error.

**Comment by EmFl** [comment]
Hello,
Had a similar issue and this was due to pibooth being configured with a resolution unsupported by my webcam.
Could you check the output of (adapt device path as needed)
`v4l2-ctl --list-formats-ext -d /dev/video0` 
And then ensure that you have a match in the pibooth config file on the resolution line

```
# Resolution for camera captures (preview will have same aspect ratio)
resolution = (640, 480)
```

**Comment by anxuae** [comment]
Thanks @EmFl for your feedback. I've added your advice in the documentation: https://pibooth.readthedocs.io/en/latest/sources/start.html#final-picture-resolution
