### ISSUE TITLE
Unable to print using Canon Selphy CP1300

### ISSUE THREAD

**Issue by xsouxsou94** [pibooth/pibooth#314]
Hi everyone, 

When I try to print, it is sent to my printer, but my printer says that the image isn't compatible :/

I'm using a CP1300 connected by WiFi. Same error message when using an USB cable.

Does someone have an idea ?

Axel

**Comment by AndyKausG** [comment]
I got it working with my CP1300. 

1) Download: PPD from https://www.voss.earth/2018/08/31/kurztipp-canon-selphy-wlan-drucker-cp910-oder-cp1300-unter-linux-cups-verwenden/

2) Open Printer Configuration (GUI)
2.1) Disable add printer automatic
2.2) Remove discovered Printer
2.3) Add Canon CP via app://Canon.... (HTTP Mode)

I don't know how to describe it better. But in the END I FIGURED IT OUT TWICHE. :)

**Comment by anxuae** [comment]
@xsouxsou94 seems to be solved, please re-open if you still have an issue

**Comment by lllsJllsJ** [comment]
@anxuae @AndyKausG Can you re-upload the PPD file, the given link above cannot download anymore

**Comment by AndyKausG** [comment]
[SELPHY_CP1300.ppd.txt](https://github.com/pibooth/pibooth/files/10889042/SELPHY_CP1300.ppd.txt)
There you go....

**Comment by mtz1734** [comment]
Can I use your solution for the printer / Driver also with USB Connection?

Thanks

**Comment by AndyKausG** [comment]
I use it with USB Connection as well!
