### ISSUE TITLE
text to line in footer texte

### ISSUE THREAD

**Issue by tityann** [pibooth/pibooth#316]
hello
is it possible to have a text to line in the footer text ?
in my footer-text1 i want to have this:
```
first
&
second
```
i have done many test and don't manage it...
please

**Comment by tityann** [comment]
@werdeil 
@anxuae 
excuse me for notification but it seems that there is no many body to came here often

**Comment by anxuae** [comment]
You can not have line break in the footer. But you can put the & in a background image.

Then first in footer_text1 and second in footer_text2

**Comment by tityann** [comment]
thanks you for the answer
i wanted to keep th footer-text2 for something else
 i will do on another way
thanks
