### ISSUE TITLE
GStreamer warnings

### ISSUE THREAD

**Issue by joshuajaharwood** [pibooth/pibooth#317]
**Describe the bug**
Starting pibooth leads to a warning being displayed:

```
[ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (1824) handleMessage OpenCV | GStreamer warning: Embedded video playback halted; module v4l2src0 reported: Failed to allocate required memory.
[ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (914) open OpenCV | GStreamer warning: unable to start pipeline
[ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (501) isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created
```

This doesn't seem to prevent usage, as long as a physical display is attached to the Raspberry Pi. Just connecting over VNC makes the application crash when taking a picture.

**Steps to reproduce the bug**
1. Start pibooth from command line
2. See error mentioned above in output

**Logs**
Config: https://pastebin.com/XZtfn0ft
Logs: https://pastebin.com/SW28KHmS

**Environment**
 - OS Raspbian 11 32-bit non-Lite (bullseye, kernel 5.10.92-v7l+ armv7l)
 - RPi Camera v2.1
 - Pibooth version 2.0.4

**Comment by anxuae** [comment]
Hi @joshuajaharwood ,

Pibooth does not support connection from VNC. Or at least need specific configuration that I does not know. So please always use a real screen
