### ISSUE TITLE
Permissions to change pictures in assets

### ISSUE THREAD

**Issue by danamaki** [pibooth/pibooth#318]
Hello. When I want to change pictures in /usr/local/lib/python3.7/dist-packages/pibooth/pictures/assets I don't have permissions to do it in FTP ( With PI acces). What is the solution please. Thank you and congratulations for your work.

-------

pi@raspberrypi:/usr/local/lib/python3.7/dist-packages/pibooth/pictures/assets $ ls -l
total 320
-rw-r--r-- 1 root staff  5912 févr. 21 10:21 arrow.png
-rw-r--r-- 1 root staff 30794 févr. 21 10:21 camera.png
-rw-r--r-- 1 root staff 20774 févr. 21 10:21 capture_left.png
-rw-r--r-- 1 root staff  6205 févr. 21 10:21 capture_right.png
-rw-r--r-- 1 root staff  5431 févr. 21 10:21 finished_left.png
-rw-r--r-- 1 root staff  9435 févr. 21 10:21 finished_right.png
-rw-r--r-- 1 root staff 16994 févr. 21 10:21 hand.png
-rw-r--r-- 1 root staff 20677 févr. 21 10:21 layout1.png
-rw-r--r-- 1 root staff 17804 févr. 21 10:21 layout2.png
-rw-r--r-- 1 root staff 25287 févr. 21 10:21 layout3.png
-rw-r--r-- 1 root staff 32396 févr. 21 10:21 layout4.png
-rw-r--r-- 1 root staff 31139 févr. 21 10:21 printer_failure.png
-rw-r--r-- 1 root staff  9538 févr. 21 10:21 printer.png
-rw-r--r-- 1 root staff 27545 févr. 21 10:21 printer_touch.png
-rw-r--r-- 1 root staff 31073 févr. 21 10:21 processing.png

**Comment by werdeil** [comment]
Hello you need root access to change any file in `/usr/local/lib`
Do you have ssh access to the pi?
If yes you can upload the pictures in a folder without root access needed (for example `/home/pi`, then via ssh copy these files in the right folder (with `sudo` to give you root privileges).
```
sudo cp /home/pi/*.png /usr/local/lib/python3.7/dist-packages/pibooth/pictures/assets/
```

**Comment by danamaki** [comment]
Thank you for your information. If the file already exists will it be replaced by the new one? Thank you
