### ISSUE TITLE
"RAW" files are saved in a different folder

### ISSUE THREAD

**Issue by danamaki** [pibooth/pibooth#320]
Hello. Is it possible that the "RAW" files are saved in a different folder than the montage? Or the opposite ! thank you in advance

**Comment by werdeil** [comment]
Hi @danamaki, it is already the case, raw files are stored in the raw folder, while final image are put directly in the folder. Do you mean put them on a complete different folder?

**Comment by danamaki** [comment]
Yes in a completely different folder. thank you

**Comment by werdeil** [comment]
Hi @danamaki I'm sorry but I don't really see any reason to make the app config more complex with this. Can you tell me a use case where you need this?

**Comment by danamaki** [comment]
Yes, it's actually very simple. The photos taken are sent to "Dropbox" and I wanted to send only the montage photos and not the "Raw" folder. but I found a workaround in my Rclone command. Thanks again.
