### ISSUE TITLE
Custom plugin crash

### ISSUE THREAD

**Issue by kevhdweb** [pibooth/pibooth#322]
Bonjour,

En voulant aller plus loin avec Pibooth, j'ai ajouté le plugin exemple "pibooth_hello.py".
Mais en lançant pibooth, j'ai l'erreur suivante : 
`File "usr/local/python3.9/dist-packages/pibooth/utils.py" line 272, in load_module
loader = hook.find_module(modname, disname)
Attribute: 'DistutilsMetaFiner' object has no attribute 'find_module'`

Pouvez-vous m'aider ?
Merci

**Comment by anxuae** [comment]
Hi, but is comment from the new versions of `setuptools`. I have to find a way to fix it.

**Comment by anxuae** [comment]
Issue is fixed in the master branch, but new version `pibooth 2.0.5` need to be published on pipit

**Comment by anxuae** [comment]
new version 2.0.5 available
