### ISSUE TITLE
Layout problem

### ISSUE THREAD

**Issue by chonchon033** [pibooth/pibooth#325]
Hello
I come back to you, when I copy/paste my layout1.png, it tells me:
"layout1.png: Error opening file "/user/local/lib/python3.9/dist-packages/pibooth/pictures/assets/layouts1.png": Permission denied"
If you can explain to me? Surely I'm not doing the right thing.
Thanks very much

**Comment by anxuae** [comment]
You need the admin rights to write into `/user` directory
You can copy by command line: `sudo cp layout1.png /user/local/lib/python3.9/dist-packages/pibooth/pictures/assets/`

(adapt path to the `layout1.png`)

@werdeil should we cache the assets in the `.config/` folder where the user can easily access to it?

**Comment by werdeil** [comment]
@anxuae you were faster than me :-)

I still don't think it is a good idea to add this feature as I still think that users shall not change the layout by themselves (even if we are helping them to do it right here).

**Comment by anxuae** [comment]
@chonchon033 did you solved your issue?

**Comment by chonchon033** [comment]
Hello
Yes Perfect
thank you so much
