### ISSUE TITLE
Preview freezes during "smile" phase

### ISSUE THREAD

**Issue by 12959022** [pibooth/pibooth#327]
**Describe the bug**
We're using a Logitech C290 webcam and during the "smile" phase the preview screen freezes. This way it looks like the photo has already been taken, however this only happens a few seconds later.

Maybe this is not really a bug but more a settings mistake. How to solve this?

-using version 2.0.5

The console gives the error: Corrupt JPEG data: premature end of data segment

Thanks

**Comment by anxuae** [comment]
Hi @12959022 

You are desiring 2 issues:

1) The fact that the capture is taken a little bite later than preview stops is not really a bug, but a synchronization behavior. This can be hard to fix, I've change the behavior in PR #328 but I can not say if it improve the user experience.

2)  Corrupt JPEG data => please attach more logs (attach the file indicated after the crash)

**Comment by anxuae** [comment]
Any update?
