### ISSUE TITLE
How to define time between two photos

### ISSUE THREAD

**Issue by mhilcher** [pibooth/pibooth#339]
Hi,

an option to set a time in seconds that is the minimum time between two photos from the camera would be great.
I am testing my flashlight right now and it needs a certain time to reload before the next flash.
The time that the flash needs to reload would be the minimum time option.

Greets, Martin

**Comment by anxuae** [comment]
Hi @mhilcher 

You can adjust the `[WINDOW]preview_delay` which is the time for the preview. If you have a longer preview, your flash will have the time to reload itself.

**Comment by anxuae** [comment]
I think that this question is answered, or your need is different than the one I've understood?
