### ISSUE TITLE
Have a different picture_par_page setting depending on the number of captures

### ISSUE THREAD

**Issue by 0xecute** [pibooth/pibooth#347]
Hi,
Thanks again for the project.

I'm trying to find a way to print twice the same picture on a photo. The idea is that people will cut it manually and will both of them get a physical picture.

For example, I have a 4x6 paper, and I want an intermediate output of the picture of 2x6 size, and then it is clone and merge to print one picture of 4x6 and cut it manually.

Is it already possible?
If not, can you point me in the right direction to do it with a plugin for example?
For example in the config:
pictures_per_page: (1,2) 
which is related to 
captures = (3,1)

Thank you in advance,
Have a nice week end

**Comment by 0xecute** [comment]
I just realize the issue is raised here already:
https://github.com/pibooth/pibooth-picture-template/issues/8

Looks like there is no easy solution at the moment :(

**Comment by werdeil** [comment]
Hi,

On the contrary the answer on the topic you provide shall fit your need (at least it was intended to):
>if you want to duplicate your photo, you can use the option in the config file:
```
# Print 1, 2, 3 or 4 picture copies per page
pictures_per_page = 2
```

**Comment by 0xecute** [comment]
No it doesn't, as I want this only when there is three pictures, and when there is only one then it doesn't duplicate :)

**Comment by werdeil** [comment]
Ok then I'll update your title as it is misleading

**Comment by 0xecute** [comment]
Sure.
I finally found a solution.
I edited "pibooth-picture-template" plugin so I can have multiple times the same pictures inside a template, same for the text.
This is a more flexible solution, but maybe overkill if we just want 2 picture_per_page.

Thanks again for this great project !
Have a nice week end

**Comment by werdeil** [comment]
Nice, if possible open a pull request with your changes, it will help others

**Comment by 0xecute** [comment]
I will. I saw it was an issue for others too.

**Comment by 0xecute** [comment]
Done:
[https://github.com/pibooth/pibooth-picture-template/pull/11](https://github.com/pibooth/pibooth-picture-template/pull/11)

**Comment by anxuae** [comment]
[pibooth-picture-template](https://github.com/pibooth/pibooth-picture-template) v1.1.0 released
