### ISSUE TITLE
disable configuration with buttons

### ISSUE THREAD

**Issue by Matthieu-mi** [pibooth/pibooth#355]
Hello
I need some help 
The photo booth had its first evening but several times the children entered in the menu via the buttons. I would like to know if it is possible to disable them. I want to keep the buttons online to take pictures. I use a keyboard and a mouse so even if this disable is permed, it is not a problem.
Thank you for your comeback

**Comment by TiJof** [comment]
You can patch it, before compiling by yourself by removing
'self._menu.show()'
in file pibooth/booth.py

**Comment by BramWerbrouck** [comment]
Hi,

When I remove this line `self._menu.show()` in pibooth/booth.py I can't access the menu by using the <esc> button on a connected keyboard anymore..

I also comment the following:
If len(self._fingerdown_events) > 3:
  self._fingerdown_events =[]
  return pygame.event.Event(BUTTONDOWN, capture=1, printer=1, button=self.buttons)

What did I do wrong?

**Comment by anxuae** [comment]
Hi @BramWerbrouck 

If you set the `[CONTROLS][multi_press_delay]=3600`, the settings menu should never appears when hardware buttons are simultaneously pressed (you need to stay pressed 1h on both buttons to open it)

**Comment by TiJof** [comment]
> When I remove this line `self._menu.show()` in pibooth/booth.py I can't access the menu by using the button on a connected keyboard anymore..
It's normal, you have to configure all by the config file with this tweak... The config file is well documented

**Comment by dmlogic** [comment]
I was about to log an identical issue. First event with the new booth and the kids came very, _very_ close to hosing two days of pictures by putting it into debug mode. Pure luck I found them before they restarted it

I think this suggestion is a sensible solution and avoids additional development:

> set the configuration key [CONTROLS][multi_press_delay]=3600
