### ISSUE TITLE
Stuck on "Smile!"

### ISSUE THREAD

**Issue by GeminyCriquet** [pibooth/pibooth#356]
Hey !

After a small number of shots, the app keeps getting stuck on 'Smile!'.
Sometimes, the first shot, sometimes I can take 3/4 shots before it happening.

There are no interesting logs in the console. It's stucked on 'pibooth: Take a capture'.

 - OS Raspbian
 - Camera Nikon D90
 - Pibooth version 2.0.5
 
Here is my log :
[diagnostic.log](https://github.com/pibooth/pibooth/files/8844506/diagnostic.log)

Do you have any advice to correct this ?

Thanks !

**Comment by anxuae** [comment]
Hi @GeminyCriquet  try by setting your DSLR autofocus in manual

**Comment by Cruiser79** [comment]
@anxuae I read al lot of times, that the switch to manual for the autofocus can help with this problem. Autofocus is very useful and i will not miss it, if it is not a must.
Is there not the possibility, that pibooth runs in an timeout after some time, if it stucks on the "Take a capture" mode and restarts himself , like it did for the "Ups! And error occured" message?

**Comment by XoVooth** [comment]
I abandoned the autofocus on D90 because it bugs during the photo shoot :(
on the other hand, if you have any D90 adjustment tips, I'm interested ;)

**Comment by anxuae** [comment]
Hi @Cruiser79 
Auto-focus is really unstable with gphot2, forget it.

Or you can try to find the issue, but in that case you need to post issues on one of this 2 repo:

- [Python binding for Gphoto2](https://github.com/jim-easterbrook/python-gphoto2)
- [libgphoto2](https://github.com/gphoto/libgphoto2)
