### ISSUE TITLE
Canon 1100D: pibooth crash using gphoto2

### ISSUE THREAD

**Issue by tekilaz** [pibooth/pibooth#363]
Hello,
i'm using pibooth last version on pi3 with canon DSLR 1100D.
When i'm trying to use my pibooth, when taking preview it stuck and have message "Ooops"...

After looking pibooth.log, seems to be a gphoto2 error with usb

Sometimes it works for 1 or 2 pictures but stuck again after

[ DEBUG   ] pibooth           : Activate state 'wait'

[ DEBUG   ] pibooth           : BUTTONDOWN: generate CAPTURE button event
[ DEBUG   ] pibooth           : took 30.614 seconds
[ DEBUG   ] pibooth           : Activate state 'choose'
[ INFO    ] pibooth           : Show picture choice (nothing selected)
[ DEBUG   ] pibooth           : BUTTONDOWN: generate CAPTURE button event
[ DEBUG   ] pibooth           : took 3.212 seconds
[ DEBUG   ] pibooth           : Activate state 'chosen'
[ INFO    ] pibooth           : Show picture choice (1 captures selected)
[ DEBUG   ] pibooth           : took 4.039 seconds
[ DEBUG   ] pibooth           : Activate state 'preview'
[ INFO    ] pibooth           : Show preview before next capture
[ DEBUG   ] pibooth           : Setting option actions/viewfinder=1
[ DEBUG   ] pibooth           : Add to buffer the image '1382508816'
[ DEBUG   ] pibooth           : Add to buffer the image '1382508552'
[ DEBUG   ] pibooth           : Add to buffer the image '1382508648'
[ DEBUG   ] pibooth           : Add to buffer the image '1382509056'
[ DEBUG   ] pibooth           : Add to buffer the image '1382508600'
[ DEBUG   ] pibooth           : Add to buffer the image '1382508912'
[ DEBUG   ] pibooth           : Add to buffer the image '1382509032'
[ DEBUG   ] pibooth           : Add to buffer the image '1382508552'
[ DEBUG   ] pibooth           : Add to buffer the image '1382508600'
[ DEBUG   ] pibooth           : Add to buffer the image '1382508720'
[ DEBUG   ] pibooth           : Add to buffer the image '1382508648'
[ DEBUG   ] pibooth           : Add to buffer the image '1382508912'
[ DEBUG   ] pibooth           : Add to buffer the image '1382508384'
[ DEBUG   ] pibooth           : Add to buffer the image '1382509248'
[ DEBUG   ] pibooth           : Add to buffer the image '1382508816'
[ DEBUG   ] pibooth           : Add to buffer the image '1382508720'
[ DEBUG   ] pibooth.gphoto2   : gp_libusb1_read [libusb1.c:614]: 'libusb_bulk_transfer (port->pl->dh, port->settings.usb.inep, (unsigned char*)bytes, size, &curread, port->timeout)' failed: Input/Output error (-1)
[ DEBUG   ] pibooth.gphoto2   : gp_port_read [gphoto2-port.c:440]: Reading 389632 = 0x5f200 bytes from port failed: Error reading from the port (-34)
[ DEBUG   ] pibooth.gphoto2   : gp_libusb1_read [libusb1.c:614]: 'libusb_bulk_transfer (port->pl->dh, port->settings.usb.inep, (unsigned char*)bytes, size, &curread, port->timeout)' failed: Operation timed out (-7)
[ DEBUG   ] pibooth.gphoto2   : gp_port_read [gphoto2-port.c:440]: Reading 128000 = 0x1f400 bytes from port failed: Timeout reading from or writing to the port (-10)
[ DEBUG   ] pibooth.gphoto2   : ptp_usb_getdata [usb.c:480]: PTP_OC 0x9153 receiving data failed: PTP Timeout (0x02fa)
[ DEBUG   ] pibooth.gphoto2   : camera_capture_preview [library.c:3326]: 'ret' failed: get_viewfinder_image failed (0x02ff: PTP I/O Error)
[ DEBUG   ] pibooth.gphoto2   : gp_camera_capture_preview [gphoto2-camera.c:1403]: 'camera->functions->capture_preview ( camera, file, context)' failed: -7
[ ERROR   ] pibooth           : [-7] I/O problem
[ DEBUG   ] pibooth           : Back to failsafe state due to error:
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/pibooth/states.py", line 53, in process
    hook(cfg=self.cfg, app=self.app, win=self.win, events=events)
  File "/usr/local/lib/python3.9/dist-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/usr/local/lib/python3.9/dist-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/usr/local/lib/python3.9/dist-packages/pluggy/_manager.py", line 327, in traced_hookexec
    return outcome.get_result()
  File "/usr/local/lib/python3.9/dist-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.9/dist-packages/pluggy/_result.py", line 33, in from_call
    result = func()
  File "/usr/local/lib/python3.9/dist-packages/pluggy/_manager.py", line 324, in <lambda>
    lambda: oldcall(hook_name, hook_impls, kwargs, firstresult)
  File "/usr/local/lib/python3.9/dist-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "/usr/local/lib/python3.9/dist-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.9/dist-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/home/pi/.local/lib/python3.9/site-packages/pibooth/plugins/camera_plugin.py", line 75, in state_preview_do
    app.camera.preview_countdown(cfg.getint('WINDOW', 'preview_delay'))
  File "/home/pi/.local/lib/python3.9/site-packages/pibooth/camera/gphoto.py", line 243, in preview_countdown
    updated_rect = self._window.show_image(self._get_preview_image())
  File "/home/pi/.local/lib/python3.9/site-packages/pibooth/camera/gphoto.py", line 129, in _get_preview_image
    cam_file = self._cam.capture_preview()
gphoto2.GPhoto2Error: [-7] I/O problem
[ DEBUG   ] pibooth           : took 24.501 seconds
[ DEBUG   ] pibooth           : Activate state 'failsafe'
[ ERROR   ] pibooth           : system='Linux', node='raspberrypi', release='5.15.32-v7+', version='#1538 SMP Thu Mar 31 19:38:48 BST 2022', machine='armv7l', processor=''
 ***********************************************************************************
 *                     Oops! It seems that pibooth has crached                     *
 *     You can report an issue on https://github.com/pibooth/pibooth/issues/new    *
 *                       and post the file: /tmp/pibooth.log                       *
 ***********************************************************************************
[ DEBUG   ] pibooth           : took 2.029 seconds
[ DEBUG   ] pibooth           : Activate state 'wait'
[ DEBUG   ] pibooth           : took 27.891 seconds
[ DEBUG   ] pibooth           : Activate state 'failsafe'
[ ERROR   ] pibooth           : system='Linux', node='raspberrypi', release='5.15.32-v7+', version='#1538 SMP Thu Mar 31 19:38:48 BST 2022', machine='armv7l', processor=''

Could you please help me ? Its for a friend wedding and only 2 days left :(

i've tried to downgrade pygame-menu but no effect
 pip3 install pygame-menu==3.3.2
so i'm back to pygame-menu==4.0.7,

**Comment by tekilaz** [comment]
please find log from pibooth -v
https://pastebin.com/bUDTk33L

**Comment by werdeil** [comment]
Hi @tekilaz , sorry for the late answer, can you confirm you are using a SD card on the 1100D?

**Comment by tekilaz** [comment]
Hi, thanks for your answer. Yes, 1100D with SD card (microSD with adapter)
After several tries, all arrors were linked to USB transfer...

So after replacing USB cable with a better one (beetween pi & DSLR Camera), problem is almost fixed !
When i'm taking a single Photo it's ok, but with 2 photos (two in one frame), it happens sometimes.

**Comment by werdeil** [comment]
Yes as stated in the log the issue is occurring when pibooth downloads the photos from the DSLR. It can be an issue on the cable and/or on the SD card (or the adapter in your case). As we are downloading all photos at the end it may appear more when taking 2 or more photos than 1. My best guess would be to test with another SD card too (and if possible not a microSD and an adapter).

**Comment by anxuae** [comment]
Hi @tekilaz 

Did you solved your issue?

**Comment by tekilaz** [comment]
Hello. Sorry for my late réponse!
Yes its solved.
My issue was from my USB cable.
Honestly 1100d is not the best camera for pibooth. Preview is really slow and Blur. And my picture seems to be Blur too, like a Bad webcam.
But you Can close this issue. I think i will upgrade (or downgrade) with a picamera.
Thanks for your help!
