### ISSUE TITLE
Error pibooth - invalid resolution requested

### ISSUE THREAD

**Issue by rafetagarci** [pibooth/pibooth#365]
/tmp/pibooth.log
[WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (501) ispipelineplaying opencv I gstreamer warning: gstreamer: pipeline have not been created

i get this and i don´t know  to do. The pibooth doesn´t work

**Comment by werdeil** [comment]
Hi @rafetagarci, we may need more info on your issue, seems that you paste the path of your log instead of the log itself.

**Comment by rafetagarci** [comment]
that´s with a webcam. And conect a picam get this 
file "/usr/lib/python3/dist-packages/picamera/camera.py", line 2270, in _set_resolution
raise picameravalue error(
picamera.exc.picameravalueError: invalid resolution requerted: piresolution(width=1934, heigh=2464)

**Comment by werdeil** [comment]
Hi @rafetagarci, as stated in the error you are using a resolution not supported by your camera. You need to put one that is compatible with your camera. Depending on the model you may find compatible resolutions here: https://picamera.readthedocs.io/en/release-1.13/fov.html#sensor-modes

**Comment by anxuae** [comment]
Hi @rafetagarci 

Add the correct resolution in the config `[CAMERA][resolution]` according to the camera manufacturer . For a picamera, resolutions are listed here: https://picamera.readthedocs.io/en/release-1.13/fov.html#sensor-modes
