### ISSUE TITLE
Hi @rafetagarci, we may need more info on your issue, seems that you paste the path of your log instead of the log itself.

### ISSUE THREAD

**Issue by rafetagarci** [pibooth/pibooth#366]
Hi @rafetagarci, we may need more info on your issue, seems that you paste the path of your log instead of the log itself.

_Originally posted by @werdeil in https://github.com/pibooth/pibooth/issues/365#issuecomment-1167144340_
that´s with a webcam. And conect a picam get this
file "/usr/lib/python3/dist-packages/picamera/camera.py", line 2270, in _set_resolution
raise picameravalue error(
picamera.exc.picameravalueError: invalid resolution requerted: piresolution(width=1934, heigh=2464

**Comment by rafetagarci** [comment]
![1656492477062](https://user-images.githubusercontent.com/108268730/176394180-2b175268-f057-4c06-9509-00638f0d3c51.jpg)

**Comment by werdeil** [comment]
Closing the issue as it is followed up in #365
