### ISSUE TITLE
String values for ISO

### ISSUE THREAD

**Issue by nicohofdtz** [pibooth/pibooth#373]
pibooth should accept string values for ISO.

> _Why not use two fitting values? A bit of context._
> For my setup I want to use a bright strobe which requires a low ISO but the continues light is much less bright so I need to set a way higher ISO for the preview. I run my pibooth setup with a Sony a6300 and Sonys don't support setting ISO values directly. Instead the values have to be changed in +/-1 steps. The speed for this is about 2 steps per second (gphoto2 is responsible for that) so changing the ISO from 100 to 200 takes about 2 seconds already. Luckily ISO auto is only one step below ISO 100 and would work best with changing ambient light conditions anyway.

The problem is that the config parser checks if ISO values are of type int. The value for auto ISO of my camera (Sony a6300) is "Auto ISO", though.
So I changed the following line in camera_plugin.py:
`cam.initialize(cfg.gettuple('CAMERA', 'iso', int, 2),`
to
`cam.initialize(cfg.gettuple('CAMERA', 'iso', (int, str), 2),`
This works and pibooth now accepts string arguments for ISO values.

I would be happy to create a pull request if there are no objections.

BTW: Here's a working minimal example which basically reproduces the code in gphoto.py and sets the camera ISO to auto:
`import gphoto2 as gp

camera = gp.Camera()
camera.init()

def set_config_value(section, option, value):
    config = camera.get_config()
    child = config.get_child_by_name(section).get_child_by_name(option)
    choices = [c for c in child.get_choices()]
    data_type = type(child.get_value())
    value = data_type(value)  # Cast value
    print(choices and value not in choices)
    child.set_value(value)
    camera.set_config(config)

set_config_value('imgsettings', 'iso', 'Auto ISO')
# set_config_value('imgsettings', 'iso', '200')

camera.exit()`

**Comment by werdeil** [comment]
Hi @nicohofdtz, you can open a PR if it works on your end I guess we can soften this criteria.
