### ISSUE TITLE
Getting a square output image

### ISSUE THREAD

**Issue by etieng** [pibooth/pibooth#378]
First, thanks for all the work done, it has been a really good time using pibooth at the past new years eve !

I'm playing around and wish to go for an output **square** picture.
I've been playing around with virtual printer setup (_cups_pdf_) with custom paper (100x100mm) but didn't changed the output picture.
I've been trying with a mask, but it takes ages to achieve the result and is finally not square (overlay PNG was 360x240 in size)
I cannot change input capture size (I'm using DroidCam v4l2loopback) because input picture get stretched and not cropped.

Do you have any advice for how to change the final picture size and let pibooth crop the captured picture ?

**Comment by anxuae** [comment]
Unfortunately the paper size is always set 4 * 6 in

**Comment by BramWerbrouck** [comment]
> Hello @etieng
> 
> Unfortunately the paper size is always set 4 * 6 in

Is it possible to change the paper size?

**Comment by anxuae** [comment]
As a quick fix, you can change the code here : https://github.com/pibooth/pibooth/blob/8ad42a83e8e89164b14da3f5bf4c591daad686d8/pibooth/pictures/__init__.py#L163

**Comment by anxuae** [comment]
Hi @etieng  

Try using the [pibooth-picture-template](https://pypi.org/project/pibooth-picture-template/), you can specify the size of the page in the template.

Please, re-open if you have any issue
