### ISSUE TITLE
Autostart failed if I set another picture path

### ISSUE THREAD

**Issue by andhey** [pibooth/pibooth#380]
Hello,
for your information. If I adjust the path in the Config so that the pictures are saved on a USB stick, the autostart does not work. When I reset the data path, everything works normally again.

**Environment**
 - OS Raspbian Bullseye
 - Camera Canon EOS 1000D
 - Pibooth version 2.05

**Comment by anxuae** [comment]
Hi @andhey 

I'm guessing that USB is not yet ready when `pibooth` starts. Can you add a delay before starting (maybe 10s) by editing the startup file as described here https://www.linuxuprising.com/2020/11/how-to-launch-startup-applications-with.html ?

If it's working, I will add an option in the configuration to do it.

Thanks for your feedback

**Comment by anxuae** [comment]
Auto start file is located here: `~/.config/autostart/pibooth.desktop`

**Comment by andhey** [comment]
Hi @anxuae,

Unfortunately, this does not have the desired effect. Pibooth does not start automatically even when the "delay" is inserted.

andhey

**Comment by anxuae** [comment]
Hi @andhey 

Just after your raspberrypi start-up, (with path set to your USB stick), cay you have a look in the `/tmp` directory and look for a `pibooth.log` file? If it's exists, please paste it here.

**Comment by anxuae** [comment]
Also, maybe the `X-GNOME-Autostart-Delay` is not recognized on raspberrypi.

In same autostart file, you can try to replace the line `Exec=pibooth` by:

`Exec=bash -c "sleep 15 && pibooth"`

**Comment by andhey** [comment]
pibooth.log:

[ INFO    ] pibooth           : Installed plugins: 
[ INFO    ] pibooth           : Starting the photo booth application on Raspberry pi 4B

**Comment by andhey** [comment]
`Exec=bash -c "sleep 20 && pibooth"`
works. Perfect. A lot of thanks

**Comment by anxuae** [comment]
Merged in master (see #384), new configuration option `autostart_delay` will be available in next pibooth release
