### ISSUE TITLE
Control neopixel rings using SPI bus instead of PWM

### ISSUE THREAD

**Issue by peteoheat** [pibooth/pibooth#385]
Not really an issue as I am also providing the solution through a new plugin.

Many neopixel implementations on raspberry pi use the Adafruit neopixel library. This uses GPIO 18 (PWM CLK). Using this requires the ability to run as the root user and also may require you to disable the onboard audio.

It is possible to the the SPI bus on the raspberry pi instead of PWM by using the [Adafruit neopixel_spi](https://docs.circuitpython.org/projects/neopixel_spi/en/latest/) library instead. The benefits of doing so seem to be that you do not need to run the plugin or pibooth as the root user or to disable audio.

I have created a PiBooth plugin called [pibooth-neopixel_spi](https://github.com/peteoheat/pibooth-neopixel_spi) to do this.

**Comment by anxuae** [comment]
Thanks for your project, I've added a link on the  pibooth main page
