### ISSUE TITLE
Unable to start, DSLR problem

### ISSUE THREAD

**Issue by Sloubi21** [pibooth/pibooth#387]
Hello,

I already had an RPi with Pibooth and that worked fine, now I changed the RPi and therefore reinstalled Pibooth, I kept the same hardware and followed the tutorial : https://pibooth.readthedocs.io/en/latest/

But Pibooth is not launching (OSError: Neither Raspberry Pi nor GPhoto2 nor OpenCV camera detected
), I updated all softwares, it's the same DSLR with SD card and good USB cable ...

You can see the followings ...

Thanks and have a good day !

```
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
pygame-menu 4.0.7
[ INFO    ] pibooth           : Installed plugins: 
[ INFO    ] pibooth           : Starting the photo booth application on Raspberry pi 4B
[ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (1824) handleMessage OpenCV | GStreamer warning: Embedded video playback halted; module v4l2src0 reported: Cannot identify device '/dev/video0'.
[ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (914) open OpenCV | GStreamer warning: unable to start pipeline
[ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (501) isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created
[ WARN:0] global ../modules/videoio/src/cap_v4l.cpp (893) open VIDEOIO(V4L2:/dev/video0): can't open camera by index
[ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (1824) handleMessage OpenCV | GStreamer warning: Embedded video playback halted; module v4l2src1 reported: Cannot identify device '/dev/video1'.
[ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (914) open OpenCV | GStreamer warning: unable to start pipeline
[ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (501) isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created
[ WARN:0] global ../modules/videoio/src/cap_v4l.cpp (893) open VIDEOIO(V4L2:/dev/video1): can't open camera by index
[ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (1824) handleMessage OpenCV | GStreamer warning: Embedded video playback halted; module v4l2src2 reported: Cannot identify device '/dev/video2'.
[ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (914) open OpenCV | GStreamer warning: unable to start pipeline
[ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (501) isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created
[ WARN:0] global ../modules/videoio/src/cap_v4l.cpp (893) open VIDEOIO(V4L2:/dev/video2): can't open camera by index
Traceback (most recent call last):
  File "/usr/local/bin/pibooth", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/pibooth/booth.py", line 490, in main
    app = PiApplication(config, plugin_manager)
  File "/usr/local/lib/python3.9/dist-packages/pibooth/booth.py", line 131, in __init__
    self.camera = self._pm.hook.pibooth_setup_camera(cfg=self._config)
  File "/usr/local/lib/python3.9/dist-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/usr/local/lib/python3.9/dist-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/usr/local/lib/python3.9/dist-packages/pluggy/_manager.py", line 327, in traced_hookexec
    return outcome.get_result()
  File "/usr/local/lib/python3.9/dist-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.9/dist-packages/pluggy/_result.py", line 33, in from_call
    result = func()
  File "/usr/local/lib/python3.9/dist-packages/pluggy/_manager.py", line 324, in <lambda>
    lambda: oldcall(hook_name, hook_impls, kwargs, firstresult)
  File "/usr/local/lib/python3.9/dist-packages/pluggy/_callers.py", line 55, in _multicall
    gen.send(outcome)
  File "/usr/local/lib/python3.9/dist-packages/pibooth/plugins/camera_plugin.py", line 26, in pibooth_setup_camera
    cam = camera.find_camera()
  File "/usr/local/lib/python3.9/dist-packages/pibooth/camera/__init__.py", line 52, in find_camera
    raise EnvironmentError("Neither Raspberry Pi nor GPhoto2 nor OpenCV camera detected")
OSError: Neither Raspberry Pi nor GPhoto2 nor OpenCV camera detected
```

**Comment by Sloubi21** [comment]
Maybe I found the way ... I have to flash with Buster PI OS ?

**Comment by anxuae** [comment]
Did you try to get a capture using photo command line?

**Comment by anxuae** [comment]
Hi  @Sloubi21 ,

Do you have some news about this issue?

**Comment by Sloubi21** [comment]
Hi @anxuae,
I have to try it, what's the command line ?
Thanks

**Comment by werdeil** [comment]
> Maybe I found the way ... I have to flash with Buster PI OS ?

There is indeed an issue with Bullseye (new library for the camera). So I guess you shall not have issues if you reinstall Buster.
If you are still on BullsEye you can try the command listed here: https://www.raspberrypi.com/documentation/accessories/camera.html#getting-started
If you are on Buster, it shall be [raspistill](https://www.raspberrypi.com/documentation/accessories/camera.html#raspistill)

**Comment by Sloubi21** [comment]
Hi @werdeil,
I'm still on BullsEye, see the results of "libcamera-hello" :
Made X/EGL preview window
[0:30:17.284515106] [67178]  INFO Camera camera_manager.cpp:293 libcamera v0.0.0+3700-f30ad033
ERROR: *** no cameras available ***

**Comment by Sloubi21** [comment]
I also try the "pibooth-diag" command :

pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
pygame-menu 4.0.7
Pibooth version installed: 2.0.5
Installed plugins: 
gPhoto2 not installed, cannot diagnose connected DSLR

I have reinstalled gPhoto2 and same problem ...

**Comment by werdeil** [comment]
Ok I reread your first message, I missed the part where you said that you are using a DSLR sorry. 
In this case you need to have gphoto2 installed and the DSLR connected. If `pibooth-diag` doesn't see gPhoto2 installed it means that you missed something. 
Is the command `gphoto2 --auto-detect` returning your dslr?
Did you install pibooth with the command: `sudo pip3 install pibooth[dslr,printer]` ?

**Comment by Sloubi21** [comment]
The comand return : 

Modèle                        Port                                             
----------------------------------------------------------
Nikon DSC D3200                usb:001,005   

Yes I've installed with DSLR and PRINTER ...

Thanks

**Comment by anxuae** [comment]
Thus issue is solved?

**Comment by Sloubi21** [comment]
> Thus issue is solved?

Unfortunately no ... I keep searching

**Comment by werdeil** [comment]
if `gphoto2 --auto-detect` returns something then it seems correctly installed.

Can you check that you have the gphoto2 python package correctly installed by running the command: `python -m gphoto2`?

**Comment by Sloubi21** [comment]
I've formated with Buster OS ... it's ok for launch pibooth and use the DSLR but now I can't use the printer :(

The access link of the printer is "gutenprint53usb..." But the file in Cups is "gutenprint53+usb" ... I try to rename the file in "gutenprint53usb..."

**Comment by Sloubi21** [comment]
![Uploading 16622208497218982333918587629269.jpg…]()
It's impossible to put a + ...

**Comment by anxuae** [comment]
@Sloubi21 

Not sure to understand, what is your issue?
(name of the printer has to be identical to the one defined in CUPS server)

**Comment by anxuae** [comment]
Please reopen if you still have an issue
