### ISSUE TITLE
Add command to reprint previous generated photo.

### ISSUE THREAD

**Issue by Kandax86** [pibooth/pibooth#390]
Hello

I did not find a way to reprint a previous photo stored with a command line. It could be helpful to send people photo after event. I tried with some preview picture software but printing was not possible or can't send data correctly on canon selphy 1300 werhase it works with pibooth.

So I'm looking for a command where I tell a picture path to start printing with same parameters than pibooth normal execution.

I don't know if I'm clear enough 

Thanks for your help.

**Comment by werdeil** [comment]
As `pibooth` is only sending the generated picture to CUPS (and CUPS handle the parameters) I guess what you want is already present in CUPS command line tools:
```lp <filename>```
Can you confirm it fill you need?

**Comment by Kandax86** [comment]
hello,
thanks for your answer i'll try it, i thought we need to set print paper size resolution & co....

**Comment by werdeil** [comment]
The printer configuration is set on CUPS side, we gave an example [here](https://pibooth.readthedocs.io/en/latest/sources/start.html?#printer) but if it worked when using live you shall not have to reconfigure it.

**Comment by Kandax86** [comment]
yep worked perfectly you are the "man" :) thank you !!!!

 `Je crois que tu es français alors merci :) beau travail cet appli tu as participé à la réussite de mon mariage ce week end !!! :)`

**Comment by Kandax86** [comment]
![IMG_20220825_115053](https://user-images.githubusercontent.com/94704501/188949213-a4b2e56f-5c36-4563-a294-a008136a8d4b.jpg)
![IMG_20220825_115047](https://user-images.githubusercontent.com/94704501/188949218-133cb437-abf2-41d3-b11e-02ee93870bf1.jpg)
