### ISSUE TITLE
Printer supply level in PiBooth Menu

### ISSUE THREAD

**Issue by Exitras** [pibooth/pibooth#392]
**Describe the solution you'd like**
I'm using the DNP DS620 printer and would love to see the remaining supply level (paper) for example directly in the PiBooth menu. I can currently only guess based on the size of the supply paper roll. I don't know if it is possible to read the printer's supply level with a Pi but it is possible with MacOS or Windows which means that the printer supports this feature.

**Comment by anxuae** [comment]
Hi @Exitras 

Thanks for your feedback. I will look if the levels can be retrieved from CUPS server.

**Comment by TheSuperpapi** [comment]
Hello Exitras.

If it could help you :

A printing counter has been added in pibooth few Time ago.

It was for this kind of need, and is compatible with all printer.

We just have to think about resetting the counter after the "cartbridge or papier roller" change.

Regards

**Comment by anxuae** [comment]
Indicator could be added at screen in case of `printed` counter reached a specific value. But finding the correct value will remain empiric. Thus it is not a perfect solution.
