### ISSUE TITLE
Add EMAIL function 

### ISSUE THREAD

**Issue by theblackhat17** [pibooth/pibooth#394]
Hey! I'm student in HIGHSCHOOL, I want to beggin your project for my classroom.
Do you think that we can add EMAIL function in the purpose to send pics by email to the other students?
Thanks a lot

**Comment by Cruiser79** [comment]
There were already such a discussion in another issue. Maybe the answer is also interesting for you
https://github.com/pibooth/pibooth/issues/42#issuecomment-1105711065

**Comment by anxuae** [comment]
Hi,

Definitely, it should be implemented in your own custom plugin, because email configuration and access depends on your custom OS / configuration and can not be implemented in ea generic way.
