### ISSUE TITLE
Picamera: Invalid resolution?

### ISSUE THREAD

**Issue by chonchon033** [pibooth/pibooth#398]
**Describe the bug**
Give a clear and concise description of what the bug is.

**Steps to reproduce the bug**
4. See error.

**Logs**
1. Set the `debug` mode in the config
2. Post your config file
3. Copy-paste all the logs from the console
4. Post the `diagnostic.log` file if you are using a DSLR camera (generated by running the command `pibooth-diag`)

**Environment**
 - OS [e.g. Raspbian Buster]
 - Camera [e.g. Rpi camera]
 - Pibooth version [2.0.6]
quand je lance pibooth 2.0.6, j'ai un message erreur "invalid resolution requested: Piresolution(width=1934, height 2464)
Merci

**Comment by werdeil** [comment]
@chonchon033 seems that you are using a resolution not compatible with your camera, can you confirm the environment you are using?
OS [e.g. Raspbian Buster]
Camera [e.g. Rpi camera]
Pibooth version [e.g. 2.0.6]

and check that the resolution set (1934x2464) is compatible with your camera.
