### ISSUE TITLE
HELP: How to set FTP remote path

### ISSUE THREAD

**Issue by delmeer** [pibooth/pibooth#404]
Hi, 

Trying to upload the pictures to an ftp folder on my Synology nas.

Looks like the script is working but how to set the remote path?
Picures need to be uploaded to /photo/pibooth/project1

"""Plugin to upload pictures on a FTP server."""

import os
from ftplib import FTP
import pibooth

__version__ = "0.0.2"

@pibooth.hookimpl
def pibooth_startup(app):
    app.ftp = FTP()
    app.ftp.set_debuglevel(0)
    app.ftp.connect("192.168.178.55", 21)
    app.ftp.login("admin", "w@chtw00rd")

@pibooth.hookimpl
def state_processing_exit(app):
    name = os.path.basename(app.previous_picture_file)

    with open(app.previous_picture_file, 'rb') as fp:
        app.ftp.storbinary('STOR {}'.format(name), fp, 1024)

@pibooth.hookimpl
def pibooth_cleanup(app):
    app.ftp.close()

Is there an option like app.ftp.path("/photo/project1")?

Best wishes, Martijn

**Comment by anxuae** [comment]
Hi, you can have a look to FTP library https://docs.python.org/3/library/ftplib.html

You have the `ftp.cwd` command to change working directory

**Comment by delmeer** [comment]
@anxuae Thanks!!

Shoud be something like:

app.ftp.connect("192.168.178.55", 21)
app.ftp.login("administrator", "1234567890")
app.ftp.cwd("/photo/project1")

Gone give it a try tonight

**Comment by delmeer** [comment]
Problem solved. Idea to change it in the default script?

"""Plugin to upload pictures on a FTP server."""

import os
from ftplib import FTP
import pibooth

__version__ = "0.0.3"

@pibooth.hookimpl
def pibooth_startup(app):
    app.ftp = FTP()
    app.ftp.set_debuglevel(0)
    app.ftp.connect("ftp.pibooth.org", 21)
    app.ftp.login("pibooth", "1h!gR4/opK")
    app.ftp.cwd("/path/to/remote/folder")

@pibooth.hookimpl
def state_processing_exit(app):
    name = os.path.basename(app.previous_picture_file)

    with open(app.previous_picture_file, 'rb') as fp:
        app.ftp.storbinary('STOR {}'.format(name), fp, 1024)

@pibooth.hookimpl
def pibooth_cleanup(app):
    app.ftp.close()
