### ISSUE TITLE
Launch Pibooth on VM

### ISSUE THREAD

**Issue by alexj47** [pibooth/pibooth#409]
Hi,

I build a Photo Booth with Pibooth and it works fine. However, I would like to customize and test things on the go with my Macbook. So I installed Raspbian on a VM on my M1 Max MacBook and installed Pibooth as explained. However, Pibooth doesn't launch because the pigpio deamon doesn't work. Does anybody have an idea how to make it work?

<img width="682" alt="Bildschirm­foto 2022-12-01 um 20 52 51" src="https://user-images.githubusercontent.com/84335202/205148331-78ae0832-45b2-4787-9e38-4eb262d07df0.png">

**Comment by anxuae** [comment]
Hi @alexj47,

Never tested on a VM. I'm supposing that, because you are runing on Pi OS, the GPIO lib try to connect to physical pins which does not exist. And so it crashes.

Another solution is to run directly `pibooth` on Ubuntu or OSX, it's working without a VM
