### ISSUE TITLE
Crash after installing FTP plugin

### ISSUE THREAD

**Issue by alexj47** [pibooth/pibooth#410]
Hi, I added the FTP plugin as described, but I keep getting an error when trying to launch Pibooth. I attached the log file.

[pibooth.log](https://github.com/pibooth/pibooth/files/10136797/pibooth.log)

**Comment by anxuae** [comment]
Hi @alexj47 

You have a connection issue with your FTP server. It is out of the pibooth scope.
You can for instance check that your FTP server is running on port 22.
Then your firewall does not block the connection
