### ISSUE TITLE
Crash with arducam imx519 on bullseye PI 3B v1.2

### ISSUE THREAD

**Issue by edwardhaase** [pibooth/pibooth#416]
Systemconfiguration: PI 3B V1.2, Arducam 16mpx with imx519

Installation as described by arducam (install_pivariety_pkgs.sh) and working/taking picture with

`libcamera-still -t 1000 -f -n -o test2.jpg`

but no autofocus yet.

Pibooth installed as described in the "Read the docs"-Page on github.

1. Pibooth is starting well,
2. select picture by button press on circuit breadboard
3. selecting 1 shot picture
4. resulting in crash with attached 'pibooth.log'

How to proceed and fix this problem?

Thx, Edward

[pibooth.log](https://github.com/pibooth/pibooth/files/10377375/pibooth.log)
[config.txt](https://github.com/pibooth/pibooth/files/10377376/config.txt)

**Comment by werdeil** [comment]
Hello as stated in the documentation pibooth is not compatible with bullseye. https://pibooth.readthedocs.io/en/latest/sources/install.html?#software

**Comment by edwardhaase** [comment]
Okay, sorry, didn't read that.
