### ISSUE TITLE
Support Bullseye and new V3 camera module 

### ISSUE THREAD

**Issue by agrovista** [pibooth/pibooth#417]
Would like to use new V3 camera module and Bullseye with pi booth

**Comment by klemva** [comment]
Hi, me too, has anyone tested it yet? It looks like very good cam:)

**Comment by yaazzz** [comment]
Seems to use picamera2. Never been able to get it working with an arducam and assume we will be in the same situation with that one.

**Comment by Surimiii** [comment]
I just installed camera v3, very nice with autofocus and hdr. But doesn't work with pibooth 😭

**Comment by anxuae** [comment]
Plan to v3.0.0

Duplicate https://github.com/pibooth/pibooth/issues/290
