### ISSUE TITLE
Fullscreen goes black screen

### ISSUE THREAD

**Issue by navarrillo** [pibooth/pibooth#418]
Screen goes black with fullscreen WINDOW option.
Esc button doesn't work the config menu.
I can see in the log that i am starting the process of boothing and choosing pictures, clicking randomly on the screen.

**Steps to reproduce the bug**
1. Go to config
2. Set fullscreen on WINDOW size parameter
3. execute pibooth

**Logs**
There's no error in logs.

**Environment**
 - OS: Debian Buster
 - Pibooth version 2.0.6

**Comment by navarrillo** [comment]
Anyone has any advise?

**Comment by jacare0000** [comment]
The same happen to me.
But If i touch the screen it wake up and Works good.
That only happen When i start pibooth in fullscreen.

**Comment by anxuae** [comment]
Hi @navarrillo 

Can you attache the log file?

What is the resolution of your screen?

**Comment by navarrillo** [comment]
I close the issue as i abandoned the thread.

**Comment by navarrillo** [comment]
I close the issue as i abandoned the thread.
