### ISSUE TITLE
Bypass some states for capture without delay

### ISSUE THREAD

**Issue by BermudaStudio** [pibooth/pibooth#419]
Hello,
I would like to bypass the "select the layout" and "preview" states (screens). 

The goal is to shoot portrait with zero delay between button press and DSLR capture.

Solution #1 = a plugin ?
Solution #2 = the possibility to set config option "preview_delay" to value "0" ?

Thanks for your help.
Rémi

**Comment by werdeil** [comment]
Hi @BermudaStudio, you can reach almost what you want through the settings, but there is no easy way to put less than 1s of preview delay.

Can you explain more the use case you want ? Because I don't see why waiting 1s is not acceptable.

**Comment by BermudaStudio** [comment]
Hi.
I would like to set up unconventionals photobooths with physical countdowns, external sensors, etc.
No live preview needed.
Regards
Rémi

**Comment by anxuae** [comment]
Hi @BermudaStudio 

If you defined in the configuration only one possible layout, the "select the layout" screen will not be shown

**Comment by anxuae** [comment]
TO definitly hide the preview, there is no other choice than changing the pibooth code to accept preview_delay=0

**Comment by BermudaStudio** [comment]
Thanks.
