### ISSUE TITLE
Strip Pictures : print twice 

### ISSUE THREAD

**Issue by dominiquegrota** [pibooth/pibooth#424]
Hi, 
I use now for more than one year pibooth, it's Great !
I bought a DS620 for lots of prints (I have a canon selfy...)
I created a specific layout with 3 pictures on a 2x6 inches picture. It works gerat but if I ask 2 prints per page, I get  twice 4"x6" with my strip centered in the 4x6". Is it possible to get twice 2"x6" ? 
Thank-you
![WIN_20230212_20_30_25_Pro](https://user-images.githubusercontent.com/95182393/218332831-ad2e46cf-3275-4906-87e4-2cb1fd887392.jpg)
It's probably easyer to understand with a picture !
I would like to get this when I print 2 pictures per page
![WIN_20230212_20_41_57_Pro](https://user-images.githubusercontent.com/95182393/218333344-6d91b4ea-049b-4dcd-86a8-1a1ccbce1ddb.jpg)

Dominique

**Comment by werdeil** [comment]
Hi @dominiquegrota, as we don't have this printer I can't help but my best guess would be to tweak CUPS settings, as pibooth is sending the generated image to CUPS without further processing.

**Comment by anxuae** [comment]
Hi @dominiquegrota, If you are using the option `pictures_per_page` , the code is done to always make the copy in the opposite orientation than your picture.

So, your picture is Portrait oriented, so copy will be done on landscape way.

With the `pibooth-picture-template`, you can chose the layout that you want and fit your need 

Note that the option `pictures_per_page` will be removed in pibooth v3.0.0. And it will be possible to code your one layout using new hook `pibooth_setup_printer` like defined here: https://github.com/pibooth/pibooth/blob/3.x/docs/sources/plugins/pibooth_custom_printer.py
