### ISSUE TITLE
Bug with effects

### ISSUE THREAD

**Issue by rodhy** [pibooth/pibooth#425]
**Describe the bug**
Error while I set effects

**Steps to reproduce the bug**
I set catpures effects in pibooth.cfg:
`captures_effects = ('film', 'cartoon', 'washedout', 'film')`

When I take the 4 photos all is ok but if try to makke ather serie i have an "oops its seems that piboth has crashed" message.

I have an error
`Oops! It seems that pibooth has crached `  

If I remove the effects all is ok.

**Environment**
 - OS : Raspbian Buster
 - Camera : Rpi camera
 - Pibooth version 2.0.6
 
[pibooth.log](https://github.com/pibooth/pibooth/files/10726779/pibooth.log)

**Comment by werdeil** [comment]
Indeed I think I found the bug the list of effect is only working once. I added a fix it will be on next release.

**Comment by rodhy** [comment]
Ok thanks.
Do you know when it will be released ?

**Comment by werdeil** [comment]
@rodhy I updated the code and tested this time. It shall be good.
