### ISSUE TITLE
Raspberry Pi Cam v3 support

### ISSUE THREAD

**Issue by jimbopi** [pibooth/pibooth#435]
Is there any plan to update to support the v3 cam or is it worth me tracking down a v2?

Thanks,

James

**Comment by anxuae** [comment]
Yes it is planned see #290

**Comment by anxuae** [comment]
To be more precise, one #290 will be implemented, Pi Cam v3 will be supported.
However it is not planed for now to handle auto-focus (if it is your question behind)
