### ISSUE TITLE
Number of photos printed

### ISSUE THREAD

**Issue by dreamescime** [pibooth/pibooth#441]
Hello,
I want to display the number of photos printed on the home page, like when you look at the counters
I found the parameter, but I don't see which part of the code to modify to make it display.
And thank you for this beautiful project, very easy to use.

**Comment by anxuae** [comment]
Hi @dreamescime ,

Not easy to achieve, code to display the `wait` scene is done here: https://github.com/pibooth/pibooth/blob/19851a161af6a09f8e5554d8ec2eb7194c980972/pibooth/view/background.py#L196

In `pibooth` v3.0.0, printed counter will be displayed
