### ISSUE TITLE
Print with a receipt printer

### ISSUE THREAD

**Issue by biscuitbox** [pibooth/pibooth#442]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

I tried to print a photo captured with a receipt printer, but the quality is worse than I expected. Of course, there is a limit to the resolution since it is only 180dpi, but I wish there was an option to convert the captured photo to grayscale and adjust the brightness and contrast.

Nice job. Good luck~

**Comment by anxuae** [comment]
Hi, there is no option in pibooth to do that because it is really specific to a use case 

However you can make a plugin to customize the factory used to generate pictures. You will be able to change image paramètres.

**Comment by biscuitbox** [comment]
Thanks for your answer. I'm not good at coding yet, but I'll try my best to learn.
