### ISSUE TITLE
Error with pibooth and Raspberry pi camera V3

### ISSUE THREAD

**Issue by Baselol** [pibooth/pibooth#452]
Getting this error every time I try to use pibooth, other camera apps on the pi works fine.
Tried to reinstall OS and  pibooth  nothing helps.
[pibooth.log](https://github.com/pibooth/pibooth/files/11184264/pibooth.log)
Best regards
Environment:
OS Raspbian Buster
Raspberry pi camera V3
Raspberry pi 4 8gb

**Comment by DrSkunk** [comment]
How were you able to fix this? Did you run an experimental branch with support?

**Comment by werdeil** [comment]
As said in other issues, pi cam v3 needs raspi OS Buster and its new libcamera module. Pibooth is not yet compatible (but @anxuae is working on it).
