### ISSUE TITLE
Image customization: only showing in black and white

### ISSUE THREAD

**Issue by Refurb** [pibooth/pibooth#469]
**Describe the bug**
I'm editing the branding of pibooth. I edited the layout3.png, this is the image of three stickmans you see when you set the amount of pictures to take to three. I've opened the original file in Adobe Illustrator and gave it my own branding with color. In the image you see on the left three yellow boxes. Whenever I replace the images, the Raspberry is showing a black/white version of it and a crappy resolution. 

Is it only possible to use black and white images?

Using the latest pibooth version

**Check for image here:** https://i.ibb.co/k3h5Dhp/Schermafbeelding-2023-05-05-222347.png

**Comment by anxuae** [comment]
Hi @Refurb 

The pictograms are colorized with same color than the text. So no it is not possible to have natively different colors.
You can of course edit the code to change this behavior.

As you say, this is the branding of pibooth 😄 , not a bug

Cheers
