### ISSUE TITLE
Can i use RPI Camera V3 features, autofocus. HDR?

### ISSUE THREAD

**Issue by rubkec** [pibooth/pibooth#471]
i want to buy a RPI Camera V3, but can i take advantage off the HDR feature and the autofocus feature on that camera out of the box?

**Comment by rubkec** [comment]
ok thanx, good suggestion for a webcam with good low light experience ? autofocus?

**Comment by rubkec** [comment]
is the Raspberry Pi High Quality camera compatible?

**Comment by anxuae** [comment]
Never tested a good webcam. But yes, HQ camera is compatible
