### ISSUE TITLE
Does somebody knows what this plugin exactly does pibooth-qr-download

### ISSUE THREAD

**Issue by rubkec** [pibooth/pibooth#475]
quesition, got everything working 
but installed also the following plugin
pibooth-qr-download

but is it mandatory? what does the plugin do?
how can it be uninstalled?

**Comment by MikkeBoomBoom** [comment]
It provides a QR code on screen allowing the users to download the last picture taken. In my build I used it with the Dropbox integration, worked like a charm. 

If installed with pip you can uninstall like so: https://pip.pypa.io/en/stable/cli/pip_uninstall/ or you can disable the plugin in the config file or the in-app menu.

**Comment by rubkec** [comment]
thnx but thats the pibooth-qr plugin, the plugin that i mean is https://pypi.org/project/pibooth-qr-download/0.1.2/#files

**Comment by anxuae** [comment]
No idea, the best it to download the code and look inside
