### ISSUE TITLE
Raspberry Pi Module 3 Camera

### ISSUE THREAD

**Issue by jrperk** [pibooth/pibooth#478]
I expected to be able to use the 12MP V3 camera after loading OpenCV.  The camera is recognized but it get the "Can not get camera preview image" message.  
[pibooth.log](https://github.com/pibooth/pibooth/files/11600959/pibooth.log)

**Comment by anxuae** [comment]
Hi @jrperk 

It seems that you are running on Bullseye, if I remember well, OpenCV can not be used with camera on bullseye except if you enable the legacy camera stack
