### ISSUE TITLE
Nextcloud plug-in integ

### ISSUE THREAD

**Issue by JohnHenry91** [pibooth/pibooth#483]
Hello, there is already the Nextcloud plugin, but unfortunately it can no longer be downloaded. When will it be integrated into PiBooth? :) 
Many greetings 
Henry

**Comment by anxuae** [comment]
Hi @JohnHenry91 

I did not know the author of the Nextcloud plugin. To integrate it into pibooth organization (not directly in pibooth), the author of the plugin has to contact us (me or @werdeil) and give us the code.
