### ISSUE TITLE
Pibooth doesn't work with RPI camera V3

### ISSUE THREAD

**Issue by sonbinome** [pibooth/pibooth#492]
**Describe the bug**
If I use RPI camera V3, pibooth crash

**Steps to reproduce the bug**
1. Connect camera
2. launch pibooth
3. take a picture
4. See error.

**Logs**
1. Set the `debug` mode in the config
2. Post your config file
3. Copy-paste all the logs from the console
4. Post the `diagnostic.log` file if you are using a DSLR camera (generated by running the command `pibooth-diag`)

**Environment**
 - OS [e.g. Raspbian Bullseye]
 - Camera [Rpi camera V3]
 - Pibooth version [2.0.7]
[pibooth.log](https://github.com/pibooth/pibooth/files/11926592/pibooth.log)

[pibooth.cfg.log](https://github.com/pibooth/pibooth/files/11926594/pibooth.cfg.log)

**Comment by werdeil** [comment]
Pi camera V3 and Pi Os Bullseye are not yes supported, see #290
