### ISSUE TITLE
Optimize the number of keys in the config

### ISSUE THREAD

**Issue by anxuae** [pibooth/pibooth#50]
There are lots of keys in the config. Some one can be removed to ease the `pibooth` configuration (e.g. `arrows`).

**Comment by Alex74300** [comment]
Bonjour Vincent

Je souhaiterai modifier le footer des impressions pibooth en y mettant une image png à la place du footer_text. Cela est il possible en modifiant le fichier config ou un fichier .py?
Merci 
Bonne journée

**Comment by anxuae** [comment]
We can close this ticket, the GUI is a good option to have a light weightconfig

**Comment by werdeil** [comment]
No I don't think we should close it, we should be able to remove some of the keys and arrows is a good example I think.

**Comment by anxuae** [comment]
Typically for arrows, I don't know how to detect the touchscreen (and don't display them)

**Comment by anxuae** [comment]
Keys to be removed from config:

- clear_on_startup

**Comment by werdeil** [comment]
> Keys to be removed from config:
> 
> * clear_on_startup

Removed in e758c45

**Comment by anxuae** [comment]
@werdeil do you think that this issue shall be kept opened?

**Comment by werdeil** [comment]
Closing it as we won't be able to fix it the way I wanted and I know you don't like having issue opened. I'll may find a workaround some day.
