### ISSUE TITLE
updating to 2.0.8 dont work

### ISSUE THREAD

**Issue by DJ-Dingo** [pibooth/pibooth#501]
When trying to update to v2.0.8 with pip3 install -U pibooth it is getting V2.0.7
same thing with pip3 install -U --no-cache-dir pibooth

What am i doing wrong ?

**Comment by anxuae** [comment]
Hi @DJ-Dingo 

Thanks for reporting, I've uploaded the wrong version on Pypi . It should be ok now

**Comment by DJ-Dingo** [comment]
Hey @anxuae it works. but downgraded my pillow from 9.5.0 to 9.2.0

**Comment by anxuae** [comment]
Yes no matter 9.2.0 is enough for pibooth
