### ISSUE TITLE
Include 'pibooth-oled-display' plugin in pibooth page

### ISSUE THREAD

**Issue by DJ-Dingo** [pibooth/pibooth#503]
Hey @werdeil , @anxuae 

I finished my OLED display (I2c or SPI) plugin for pibooth, **`pibooth-oled-display`**
Please add it to the lists of Third-party plugins.
https://pypi.org/project/pibooth-oled-display/

It´s a litlle more advanced than my 'lcd-display' plugin, as it can also show Images/Logo, Animated GIFs, States. an ofcouse all the 4 Counters, ``Photos Taken``, ``Printed Photos``, ``Forgotten Photos``, ``Remaining Duplicates``, Text and Date-Time, with different fonts.
(Personal i use it as a big photo counter or to show time on the display).

It is possible to add 2 OLED displays, by manual adding the extra **`pibooth_oled_display_2.py`** script to the custom plugin(s) in the config.cfg

You can also add your own user Logo/Animated GIF, States and Fonts, in the `oled-display` folder in the local pibooth config folder.

If you only, are using a 3v3 I2c oled display, it is just 4 wires to the Pi as showing in the images. I also included support for many different display types and resolutions. And in the readme showing how to use E.g. 5v and SPI displays (6 or 7 wires SPI displays). 

![pibooth-oled-display](https://raw.githubusercontent.com/DJ-Dingo/pibooth-oled-display/master/templates/Pibooth_OLED-I2c_3V3_main.png)

**Comment by werdeil** [comment]
Thanks @DJ-Dingo I finally added it in the Third-Party plugins. Closing this issue
