### ISSUE TITLE
Setup Pibooth without Printer

### ISSUE THREAD

**Issue by XWEXTX** [pibooth/pibooth#507]
Hi guys,

how i can setup Pibooth without a Printer?

**Comment by DJ-Dingo** [comment]
@XWEXTX You dont need a printer to use Pibooth

**Comment by ChrisMch** [comment]
Hi,
You can disable printer function by setting:
`printer_name = no printer`
in [PRINTER] part in the pibooth.cfg file.
You can find it there : ~/.config/pibooth/pibooth.cfg

Hope it will work :)

**Comment by dominiquegrota** [comment]
hi, 
you can just set the 
`max_pages = 0`
So the print option will not been shown !
