### ISSUE TITLE
new camera module 3

### ISSUE THREAD

**Issue by BramWerbrouck** [pibooth/pibooth#509]
HI,

I got my pibooth working with an Raspberry Pi Camera Module 2 NoIR, but now I bought a new camera: a module 3. When I want to take a picture, I got the messeage 'oops, something went wrong'

What do I do wrong? Maybe a setting somewhere??

**Comment by werdeil** [comment]
Hi @BramWerbrouck, unfortunately camera module 3 needs an update of the libcamera and pibooth is not yet compatible with it. We are working on it but we don't have an ETA unfortunately.

**Comment by BramWerbrouck** [comment]
ok, is there a list available of cameras supported by pibooth ? 

I hope that an update for the camera module 3 soon will be available.

**Comment by Mystix38** [comment]
Bonjour,
J'ai également acheter un module caméra 3 et "oups, quelque chose s'est mal passé" 😒
J'espère que la mise à jour sera vite là...

**Comment by anxuae** [comment]
Hello,

`pibooth` not compatible with PiOS Bullseye (downgrade to Buster)

See #290
