### ISSUE TITLE
Wrong link for the documentation

### ISSUE THREAD

**Issue by vwvw** [pibooth/pibooth#512]
The official documentation on readthedocs is build from the 3.x branch but the latest released version is still from main. 

This means for example that Bulleyes is recommended instead of Buster. 

Shouldn't the readthedocs link point to https://pibooth.readthedocs.io/en/stable/ ?

**Comment by anxuae** [comment]
Yes pleas use the doc at https://pibooth.readthedocs.io/en/stable

I've fixed the link in the master branch
