### ISSUE TITLE
normal or wide-angle camera

### ISSUE THREAD

**Issue by ManuFr54** [pibooth/pibooth#523]
Hello and Thanks for this great software.
Should you choose a standard camera or a wide-angle?
I'm between the 2 versions of this camera:
https://www.kubii.com/en/official-raspberry-pi-accessories/3878-camera-module-v3-raspberry-pi-3272496313699.html
The standard 75° version is €30
The 120° wide-angle version is €39

**Comment by pirlgon** [comment]
First of all, PyBooth is not yet compatible with Pycamera v3, but that's not the answer you're looking for :)

**Comment by dominiquegrota** [comment]
Hi ! 
I use a standard camera PIcam V2 Cam and it is (for my use "wide angle enough"). Here is a picture tacken about 1.5/1.8 m from the pibooth with this cam.

![CamilleDorian_105-scaled](https://github.com/pibooth/pibooth/assets/95182393/52628714-0ef1-4e3f-ba63-5bbc89121043)
Dominique

**Comment by ManuFr54** [comment]
Hi and Thank you pirlgon and Dominique,
in this case, I think I will take v2.
