### ISSUE TITLE
Documentation enhancement - DSLR configuration

### ISSUE THREAD

**Issue by Crapout** [pibooth/pibooth#531]
Hello, 

As a complete beginner in photography, i have been struggling to find the best settings for my DSLR and i have faced some errors.
Here's a couple of suggestion to add to [the documentation](https://pibooth.readthedocs.io/en/latest/index.html) in order to ease newcommers onboarding into the Pybooth adventure.

--------------------------------------------

## Useful tips : 
- Disable "auto-sleep" or "auto-off" to prevent errors while running pibooth.
- Disable Wifi feature to solve gphoto2 troubles to detect hardware.
- Use DSLR Manual mode

### Most common settings for DSLR : 
```
Shutter speed: 1/60
Focal Opening: F10
ISO: 3200

Shutter speed: 1/125
Focal Opening: F8
ISO: 3200
```

### Alternative settings, mainly depending on natural light conditions : 
```
Shutter speed: 1/60
Focal Opening: F8
ISO: 6400

Shutter speed: 1/200
Focal Opening: F8
ISO: 1600

Shutter speed: 1/200
Focal Opening: F10
ISO: 3200

Shutter speed: 1/20
Focal Opening: F14
ISO: 3200

Shutter speed: 1/30
Focal Opening: F4.0
ISO: 1600

Shutter speed : 1/200
Focal Opening: F8.0
ISO : 1600

Shutter speed: 1/125
Focal Opening: F7.1
ISO: 400
```
Credits goes to https://fotomax.fr/canon-camera-settings-with-a-magic-mirror-photobooth/ for most of these configurations.

## Troubleshooting
Frequent issues using a DSLR (unable to release shutter or unable to autofocus) : 
- there is not enough light
- the booth is empty and has a plain background
- guests are too close to the camera
- the lens cap has not been removed

--------------------------------------------

Also, thank you for this OS contribution, you guys have made an amazing work. 👍

**Comment by werdeil** [comment]
Hi @Crapout, Thanks for the feedback, I've tried to add some documentation it will be visible on the ReadTheDoc soon.
