### ISSUE TITLE
changement de l'enregistrement de la photo

### ISSUE THREAD

**Issue by Val4497** [pibooth/pibooth#552]
Bonjour, 
je recherche comment faire pour mettre mes photos directement sur ma clef usb (et/ou une copie sur ma carte sd) 
si vous pouvez m'aider 
merci beaucoup

**Comment by werdeil** [comment]
Hi @Val4497,

I'll answer in English for everyone.

You can define the folder where the images are stored in the configuration. See https://pibooth.readthedocs.io/en/latest/sources/config/config.html

You can put a list of paths if you want to save on more than a folder.

**Comment by werdeil** [comment]
Closing this answered question
