### ISSUE TITLE
Photos trop sombre (Pictures too dark)

### ISSUE THREAD

**Issue by Icksan72** [pibooth/pibooth#563]
Bonjour, 

Mes photos sont assez sombre, je cherche donc à modifier cette prise de photos.
J'utilise une camera pi
Comment peut-on modifier la valeur du brigthness  ?
Merci d'avance
Ick

**Comment by Icksan72** [comment]
J ai trouvé merci 
Je voulais modifier la brillance donc en éditant le fichier python j ai ajouté un paramètre

**Comment by werdeil** [comment]
Le problème semble réglé, je ferme le sujet

Issue seems solved, closing it.
