### ISSUE TITLE
replace footer_text2 by logo

### ISSUE THREAD

**Issue by desertseb** [pibooth/pibooth#610]
Hello,
I would like to replace the 'footer_text2' area with a logo. Is that possible, and how can I do it?

**Comment by desertseb** [comment]
How can I add a background file?

**Comment by desertseb** [comment]
I modified the background field in the PICTURE section of pibooth.cfg by setting backgrounds = background.png, and I get a feedback/error during the photo assembly.

**Comment by dominiquegrota** [comment]
Hi, 
Either you have to give the complete link to your "background.png"   (maybe : /home/pi/Pictures/background.png)
or you got the same problem I had here : https://github.com/pibooth/pibooth/issues/397
to solve it I added the plugin "picture template plugin" and the overlays are working

**Comment by desertseb** [comment]
thank you it works
